{
 "title": "Camel-K",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(application_camel_route_exchanges_completed_total, namespace)"
    }
   },
   {
    "name": "context",
    "label": "Camel Context",
    "query": {
     "query": "label_values(application_camel_route_exchanges_completed_total{namespace=\"$namespace\"}, camelContext)"
    }
   },
   {
    "name": "route",
    "label": "Camel Route",
    "query": {
     "query": "label_values(application_camel_route_exchanges_completed_total{namespace=\"$namespace\", camelContext=\"$context\"}, routeId)"
    }
   },
   {
    "name": "job",
    "label": "Integration",
    "query": {
     "query": "label_values(application_camel_route_processing_seconds{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Live Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (namespace) (application_camel_context_exchanges_completed_total{namespace=\"$namespace\", camelContext=\"$context\"})"
    },
    {}
   ]
  },
  {
   "title": "Routes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1,count by (namespace) (application_camel_route_exchanges_completed_total{namespace=\"$namespace\", routeId=\"$route\"}))"
    }
   ]
  },
  {
   "title": "Consumers Inflight",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_camel_context_exchanges_inflight_count{namespace=\"$namespace\", camelContext=\"$context\",})"
    }
   ]
  },
  {
   "title": "Completed Exchanges",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_camel_context_exchanges_completed_total{namespace=\"$namespace\", camelContext=\"$context\"})"
    }
   ]
  },
  {
   "title": "Failed Exchanges",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_camel_context_exchanges_failed_total{namespace=\"$namespace\", camelContext=\"$context\"})"
    }
   ]
  },
  {
   "title": "Camel-K Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (application_camel_context_uptime_seconds{namespace=\"$namespace\", camelContext=\"$context\"})"
    }
   ]
  },
  {
   "title": "Pods Per Node Distribution",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "count by(instance,camelContext) (application_camel_context_exchanges_total{namespace=\"$namespace\", camelContext=\"$context\"})"
    }
   ]
  },
  { "title": "Namespace Processing Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Camel-K All Exchanges Per Hour - Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (namespace) (increase(application_camel_context_exchanges_total[1h]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Camel-K All Exchanges Per Hour - Per Job",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "sum by (job) (increase(application_camel_context_exchanges_total[1h]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Camel-K Completed Exchanges Per Hour - Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum by (namespace) (increase(application_camel_context_exchanges_completed_total[1h]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Camel-K Completed Exchanges Per Hour - Per Job",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (job) (increase(application_camel_context_exchanges_completed_total[1h]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Failed Exchanges Per Hour - Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum by (namespace) (increase(application_camel_context_exchanges_failed_total[1h]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Failed Exchanges Per Hour - Per Job",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "expr": "sum by (job) (increase(application_camel_context_exchanges_failed_total[1h]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Execution Times Per Route Since Start",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Avg Exec time: $route",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (application_camel_route_processing_rate_per_second{namespace=\"$namespace\", camelContext=\"$context\", routeId=~\"$route\"})"
    }
   ]
  },
  {
   "title": "Avg Exec time: $route - All Instances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (routeId) (application_camel_route_processing_rate_per_second{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"})"
    }
   ]
  },
  {
   "title": "Avg Exec time: $route - Per Instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (routeId, job) (application_camel_route_processing_rate_per_second{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Processing Seconds Per Execution Rate: $route - All Instances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (routeId) (application_camel_route_processing_seconds{namespace=\"$namespace\", camelContext=\"$context\", routeId=~\"$route\"}) / sum by (routeId) (application_camel_route_exchanges_total{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"})"
    }
   ]
  },
  {
   "title": "Processing Seconds Per Execution Rate: $route  - Per Instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (routeId, pod) (application_camel_route_processing_seconds{namespace=\"$namespace\", camelContext=\"$context\", routeId=~\"$route\"}) / sum by (routeId, pod) (application_camel_route_exchanges_total{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Traffic Per Route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exchanges/sec: $route",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(application_camel_route_exchanges_total{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"}[1m]))"
      }
     ]
    },
    {
     "title": "$route Exchanges/sec - All Instances",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 2, "y": 21 },
     "targets": [
      {
       "expr": "sum by (camelContext) (irate(application_camel_route_exchanges_total{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"}[5m]))"
      }
     ]
    },
    {
     "title": "$route Exchanges/sec - Per Instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 7, "y": 21 },
     "targets": [
      {
       "expr": "irate(application_camel_route_exchanges_total{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"}[5m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Current Inflight: $route",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 12, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(application_camel_route_exchanges_inflight_count{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"})"
      }
     ]
    },
    {
     "title": "$route Inflight Exchanges - All Instances",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 21 },
     "targets": [
      {
       "expr": "sum by (camelContext) (application_camel_route_exchanges_inflight_count{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"})"
      }
     ]
    },
    {
     "title": "$route Inflight Exchanges - Per Instances",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 21 },
     "targets": [
      {
       "expr": "sum by (job) (application_camel_route_exchanges_inflight_count{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"})",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Execution Times Per Route Over Last 5 Minutes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Exec time: $route",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (routeId) (increase(application_camel_route_processing_rate_per_second{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"}[5m])) "
      }
     ]
    },
    {
     "title": "Avg Exec time: $route - All Instances",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 2, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (routeId) (increase(application_camel_route_processing_rate_per_second{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"}[5m])) "
      }
     ]
    },
    {
     "title": "Avg Exec time: $route - Per Instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 7, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (routeId,job) (increase(application_camel_route_processing_rate_per_second{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"}[5m])) ",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Processing Seconds Per Execution Rate: $route - All Instances",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (routeId) (increase(application_camel_route_processing_seconds{namespace=\"$namespace\", camelContext=\"$context\", routeId=~\"$route\"}[5m])) / sum by (routeId) (increase(application_camel_route_exchanges_total{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"}[5m]))"
      }
     ]
    },
    {
     "title": "Processing Seconds Per Execution Rate: $route - Per Instance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (routeId, pod) (increase(application_camel_route_processing_seconds{namespace=\"$namespace\", camelContext=\"$context\", routeId=~\"$route\"}[5m])) / sum by (routeId, pod) (increase(application_camel_route_exchanges_total{namespace=\"$namespace\", camelContext=\"$context\", routeId=\"$route\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}