kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-properties
data:
  application.properties: >-
    camel.component.kafka.brokers=dev-kafka-plain-bootstrap-dh-dev-message-bus.apps.kafka-poc.dev.datahub.redhat.com:443

    camel.component.kafka.security-protocol=SSL

    camel.component.kafka.sslTruststoreLocation=/etc/camel/conf.d/_secrets/kafka2trino-truststore/dev.jks

    camel.component.kafka.sslTruststorePassword=datahub
