---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-dev-camel-k

resources:
  - ../../base
  - operator-group.yaml

generators:
  - secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
