apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - logstash.yaml

generatorOptions:
  disableNameSuffixHash: true

generators:
  - ./secrets/secret-generator.yaml

configMapGenerator:
  - name: logstash-ingest-logstash-yml
    files:
      - logstash-conf/logstash.yml
  - name: logstash-ingest-logstash-patterns
    files:
      - logstash-conf/default
  - name: logstash-ingest-logstash-config
    files:
      - logstash-conf/00-input-lumberjack.conf
      - logstash-conf/99-output-kafka.conf
