---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: logstash
    logstash-name: logstash-ingest
  name: python
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/internaldatahub/python-35-centos7:3.5
      importPolicy: {}
      referencePolicy:
        type: Source

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: logstash
    logstash-name: logstash-ingest
  name: logstash-monitor
spec:
  lookupPolicy:
    local: false
  tags:
    - importPolicy: {}
      name: latest
      referencePolicy:
        type: Source

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: logstash
    logstash-name: logstash-ingest
  name: logstash
spec:
  lookupPolicy:
    local: false
  tags:
    - importPolicy: {}
      name: latest
      referencePolicy:
        type: Source

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: logstash
    logstash-name: logstash-ingest
  name: logstash
spec:
  output:
    to:
      kind: ImageStreamTag
      name: logstash:latest
  source:
    type: Git
    contextDir: logstash/container-image
    git:
      ref: master
      uri: https://github.com/aicoe/internal-data-hub.git
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: GIT_SSL_NO_VERIFY
          value: 'true'
        - name: LOGSTASH_VER
          value: "6.2.3"
  triggers:
    - type: ConfigChange

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: logstash
    logstash-name: logstash-ingest
  name: logstash-monitor
spec:
  output:
    to:
      kind: ImageStreamTag
      name: logstash-monitor:latest
  source:
    type: Git
    contextDir: logstash-monitor/s2i
    git:
      uri: https://gitlab.cee.redhat.com/data-hub/service-monitor.git
      ref: master
  strategy:
    type: Source
    sourceStrategy:
      env:
        - name: GIT_SSL_NO_VERIFY
          value: 'true'
      incremental: true
      from:
        kind: "ImageStreamTag"
        name: python:latest
  triggers:
    - type: ConfigChange

---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: logstash-ingest-logstash
  labels:
    app: logstash
    logstash-name: logstash-ingest
spec:
  template:
    metadata:
      labels:
        app: logstash
        logstash-name: logstash-ingest
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: logstash-name
                      operator: In
                      values:
                        - logstash-ingest
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
      volumes:
        - name: logstash-yml
          configMap:
            defaultMode: 420
            name: logstash-ingest-logstash-yml
        - name: config
          configMap:
            defaultMode: 420
            name: logstash-ingest-logstash-config
        - name: patterns
          configMap:
            defaultMode: 420
            name: logstash-ingest-logstash-patterns
        - name: queue
          emptyDir: {}
        - name: logstash-certs
          secret:
            defaultMode: 420
            secretName: logstash-ingest-logstash-certs
        - name: logstash-certs-keys
          secret:
            defaultMode: 420
            secretName: logstash-ingest-logstash-certs-keys
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - logstash
        from:
          kind: ImageStreamTag
          name: logstash:latest
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - logstash-monitor
        from:
          kind: ImageStreamTag
          name: logstash-monitor:latest
