---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - grafana-proxy-config-secret.yaml
  - grafana-cluster-role-binding.yaml

namespace: dh-stage-telemetry-grafana
