apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
  labels:
    shard: internal
spec:
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: grafana
