apiVersion: v1
kind: Secret
metadata:
    name: grafana-config
type: Opaque
data:
    grafana.ini: ENC[AES256_GCM,data:IgYFO2x8CIUJIBM5B8ry/ho6YOY/mn9O6diiAVoa/UvT86A6+3EOBsFAvFEDduv4zWuhaRRRsfRZWyTxjklOk5pQ8MrqVXNg6Gn91Z5YWjryBSFIrcIsL2Fc+Vj9yb7QbRcKH2uXqJ9itPuQJ7vxNdRDchsYaDHBPam3IaPOT7qqD0dTv3W0dHmqWJ4zHRbAogV4DCykAnxHh8RYl+pLbvVsbXURwvrKNdGctEg/2D6BuW5Zid3dcDi1LzwgjYMeY3quqsxTI+0hF67gXKPy9YYPkK9Lj2bX/WmHnzEWVNhnh5Eat6YaLT3KT9g5TJvcxid0DWB1zsujcJaSLrzqjYliQkDMWiMZ8rg+IxLDJQnMjl1vUbjXnZLciDfm++I2ZPc1Fwp1QYWpA+4o929K+M7RuLjJmqBx2Cy1zBvWjSiZI9pnbtBKwFhlVAPMZ3yLLn04nEF2li4O6geqrQBYKlTxYnh1A5BjKaLC4XrKCUAcvw04HzoCQak8CvVk3GD4eInEnfkx/GDUJGn9P1cDPez+/cJP6s1rGKBceFuN26rnJjBGahA6Qik9tCEBNq/8Ik5hkOXXuPgzSG1XD8QJOKPV0ZrvhHP/0U6HZK16bZkH9tEFw7WT9QdU3F4a51dLoFcfiGorF576fA+jWou7t42Fd8Tpvr+htu8B+cD8KSiUPrTiZvi5qNZ1NBcfP+hWWSRXbCs0BPPOvYsDRRPG/XPoSt8DWymfTh+gii63TiapuU3krceopjEg8McNRScHgHQ/6XAlzlLJt9G11m79RP5s1+qCIZUfroIa3HBjXZ6YgeqmTLOwIg==,iv:tsmrtN0G6WUakK5RrbfQAyrL4HrjeIbQd/YqxCnJNxw=,tag:fFLdIoDl3CEp+3+ovlh+fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-04T16:22:52Z"
    mac: ENC[AES256_GCM,data:2daV5IizsCv0POhoADxJTT1X3p/QRMXUqjkgmjtVjaGz0NrXo9tP/xEbsRjTbwfEsOezkgUChUzH1XvpJRPmU7KkxW1o6zw/EQIZLNi1P7s9V5mMwV3V/e//ODv8E+cnJHNn0bxfLunnGuHh+576uwJuUC2VLYxEFhsHQwdjmw4=,iv:LV+ew4MoThkh/CLDs/ZdMr9PwMM0gESCzWyAwb4+HRc=,tag:c9Cou86RbqRcVNTE7x+Glg==,type:str]
    pgp:
        - created_at: "2021-10-04T16:22:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgAig+OcJTKCi1vN1OucyG1Egjwod9kn1w11oHfK1vz07pX
            gQEydxhJqSF05/JbRuTHSN1vxTc+wP+BTXvJ5MSt5P75JZn64bD3b+eRX1O0Z3fE
            3G5AB17aL3s+iglVEol5jNTRKbBNg4PENeuZEE72oAdVj+nibi1eYY2k58H65mXS
            ZFSWUBRV/bujldMTs9AXNDj2ACKQePOPiyt9X+2z6j4oDVrIrKTWiAY+TsF+ny3J
            tOiafIWHsnPlVRiXcLbMAjECRM+9wRDn6afKM4g1Hj1gVPIpw8WV6jj1W/Dknfew
            l8os7tvEahFNFNs8kqh4LTsoush6TLnHjGpqwB+jjdJeAWu90Qo9HbLhpeMxFGWC
            39EYDiIxRqubAdxjk1GNo7SFiQADE0C0uFE2GAsIImzsUw1k3N6CFz4jRT2VH3DJ
            BcuDq62z0HTkjoVNcW1Ydvv8AF4vpQkUpcrrCR/oxw==
            =QSBk
            -----END PGP MESSAGE-----
          fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.7.1
