apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: https
    service.alpha.openshift.io/serving-cert-secret-name: grafana-tls
  name: grafana
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: grafana
