apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    app: grafana
    deploymentconfig: grafana
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 30%
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: grafana
        deploymentconfig: grafana
    spec:
      containers:
        - name: dashboard-discovery
          image: quay.io/app-sre/k8s-sidecar:0.1.178
          volumeMounts:
            - name: grafana-dashboard-definitions
              mountPath: /grafana-dashboard-definitions
          env:
            - name: LABEL
              value: "grafana_dashboard"
            - name: FOLDER
              value: /tmp/
            - name: FOLDER_ANNOTATION
              value: grafana-folder
            - name: RESOURCE
              value: configmap
            - name: UNIQUE_FILENAMES
              value: "true"
        - name: grafana
          args:
            - -config=/etc/grafana/grafana.ini
          image: quay.io/app-sre/grafana:9.3.6
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_INSTALL_PLUGINS
              value: "grafana-piechart-panel"
            - name: GRAFANA_USERS_ROLE
              value: Viewer
          ports:
            - containerPort: 3001
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-dashboards
            - mountPath: /etc/grafana/provisioning/notifiers
              name: grafana-notifiers
            - mountPath: /etc/grafana
              name: grafana-config
            - mountPath: /grafana-dashboard-definitions
              name: grafana-dashboard-definitions
        - name: auth-proxy
          image: quay.io/openshift/origin-oauth-proxy:4.8.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 150Mi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 8443
              name: web
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - '--provider=openshift'
            - '--https-address=:8443'
            - '--openshift-service-account=grafana'
            - '--upstream=http://localhost:3001'
            - '--openshift-delegate-urls={"/": {"resource": "services", "verb": "get", "name": "grafana"}}'
            - '--tls-cert=/etc/tls/private/tls.crt'
            - '--tls-key=/etc/tls/private/tls.key'
            - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
            - '-skip-auth-regex=^/metrics'
            - '--pass-user-bearer-token'
          volumeMounts:
            - mountPath: /etc/proxy/secrets
              name: grafana-proxy-secret
            - mountPath: /etc/tls/private
              name: grafana-tls-secret
      serviceAccount: grafana
      serviceAccountName: grafana
      volumes:
        - name: grafana-proxy-secret
          secret:
            secretName: grafana-proxy-config
            defaultMode: 420
        - emptyDir: {}
          name: grafana-dashboard-definitions
        - emptyDir: {}
          name: grafana-storage
        - emptyDir: {}
          name: grafana-notifiers
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
        - configMap:
            defaultMode: 420
            name: grafana-dashboards
          name: grafana-dashboards
        - name: grafana-config
          configMap:
            defaultMode: 420
            name: grafana-config
        - name: grafana-tls-secret
          secret:
            defaultMode: 420
            secretName: grafana-tls
  triggers:
    - type: ConfigChange
