apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "name": "telemeter",
                "type": "prometheus",
                "typeLogoUrl": "",
                "access": "proxy",
                "url": "http://token-refresher:8080",
                "basicAuth": false,
                "isDefault": true,
                "withCredentials": false,
            }
        ]
    }
