---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - grafana-role.yaml
  - grafana-rolebinding.yaml
  - grafana-route.yaml
  - grafana-service.yaml
  - grafana-dashboards-configmap.yaml
  - grafana-config-configmap.yaml
  - grafana-deploymentconfig.yaml
  - telemeter-groups-rolebinding.yaml
  - token-refresher-deployment.yaml
  - token-refresher-service.yaml
  - grafana-datasources-configmap.yaml

generators:
  - ./secret-generator.yaml
