apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana"}}'
    serviceaccounts.openshift.io/oauth-redirectreference.grafana_secondary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-external"}}'
imagePullSecrets:
  - name: quay.io
