apiVersion: v1
kind: Secret
metadata:
    labels:
        app: supersetdb
    annotations:
        template.openshift.io/expose-database_name: '{.data[''database-name'']}'
        template.openshift.io/expose-password: '{.data[''database-password'']}'
        template.openshift.io/expose-username: '{.data[''database-user'']}'
    name: prod-supersetdb-secret
stringData:
    database-name: ENC[AES256_GCM,data:BoxIJplh74A=,iv:H/thunGZ5unr49nUc1i/wKu4uVZ4IummHBN+Br/N+7M=,tag:+qibYhxjN7nMDBJY/oOS8g==,type:str]
    database-password: ENC[AES256_GCM,data:rXl7gBD3k6KzAr5qleqZ6rChF+4=,iv:a3Mytgw5VggyRrD6+UPQw4TZGl9ruvk6C/mwHe1g/PU=,tag:Ll2u45yMN4AV/GvGrr93Yw==,type:str]
    database-user: ENC[AES256_GCM,data:7WBduX8BTO4=,iv:NOeCNWAJxEmr3jxHu1oDiwfV2SAo7/DykcGZXuCylvE=,tag:yQ+RsLdnIZ4OLuIIt6j7hA==,type:str]
    backups-password: ENC[AES256_GCM,data:fZwcF1kbNQ==,iv:mEmn0w/TUBkEJL+lTJ4L7Hv5fHrMaNtfSkQO71KOZ28=,tag:9K5b9zgoMULrOdDos0vwqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-09-01T05:03:42Z'
    mac: ENC[AES256_GCM,data:U94M3pzDHN3vL5TfCmpiK0oAuzNUW7mHoH24UkvNOTzR5Dp3N4I1WGL29ipwZXwKBtjIXcol+Gln8SsS+vBiQwefJh+kL0fN1lNyaeZncuB8BBktVmyUcIRsIlWm34wus+88QSiwskqq1t0E5LpSo1RHFBEeEulE/+eKqwznFj4=,iv:lpNkdeiAsssq90qUQrqQGX2FjAss5p865r9dlfEfUnk=,tag:fvTGK3OLX8FWNUHmFsRPMw==,type:str]
    pgp:
    -   created_at: '2021-07-13T20:19:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgAhlM/ALol88odPvdOg2v37ic+cOC4EWzqVc+ckoZSzAVh
            7KjXBPpZ6khEjpv7DC8KyEMhBqDVPclaGYgw0z6x38bT5wWlpMY2OFJSitsx1BJC
            eBY9fy7DTSxyyRAuizfz/y2xTMF793bWxLVY7dDrXtRhZ1WYapr2i9cyfqzQC7t7
            2HXqNOgOJSl75R992ANRJVwwcN8wv5jqZLzwyiAr/LahjYhL0SGB4cygWVQGa0HT
            ZHO/6yMGQ6nHTNCQ5fHNC87VuTzwXtHBkZIgai5EE4c0MwOx9L1XVISI9He0UDL6
            +3ROTAggUUOb4QSCltMEEQ2B8pXFyFnstZj8AAnDvtJeAXXO0V9G+1mbS/o5AVKn
            Ts6s8fsfI+3UfSzPWRdsLzC0V2Z0dwr3yirThO1Gvub06y7HBefW6U+CUF6QopD1
            047jZJm4PveWtAZlHtdITfT+IN8PnbyXri/Y2FHrOw==
            =1ewX
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
