---
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: kafka2trino-pnc-logs
spec:
  dependencies:
    - 'camel:kafka'
    - 'camel:sql'
    - 'mvn:io.trino:trino-jdbc:368'
    - 'mvn:org.apache.camel.k:camel-k-runtime'
    - 'mvn:org.apache.commons:commons-dbcp2:2.9.0'

  sources:
    - content: >-
        package com.redhat.idh;

        import org.apache.camel.builder.RouteBuilder;
        import org.apache.camel.builder.AggregationStrategies;

        public class CamelKafkaToTrino extends RouteBuilder {
            @Override
            public void configure() {

                from("kafka:dynamic-pnc-logs")
                        .log("Processing ${body}")
                        .aggregate(constant(true)).completionSize(20).aggregationStrategy(AggregationStrategies.groupedBody())
                        .to("sql:insert into iceberg.kafka.pnc_logs(message, timestamp) values ((#, current_timestamp))?batch=true");
            }
        }
      name: CamelKafkaToTrino.java
  traits:
    mount:
      configuration:
        configs:
          - 'configmap:kafka-properties'
          - 'configmap:trino-beans'
        resources:
          - >-
            secret:kafka2trino-truststore@/etc/camel/conf.d/_secrets/kafka2trino-truststore
    prometheus:
      configuration:
        enabled: true
