apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

generators:
  - ./secret-generator.yaml

patchesStrategicMerge:
  - update-partition-metadata-workflow_patch.yaml

namespace: "dh-prod-argo"
