kind: Secret
apiVersion: v1
metadata:
    name: dh-docs-trigger-secret
data:
    WebHookSecretKey: ENC[AES256_GCM,data:KfHU3P3t65cKYyRqPg3Cow==,iv:jPbVlb73xdWwmeLZNHkFlg49Y2JrhP5dOafCdS14ORI=,tag:hTTDCOq5JtAVACM/0d58xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-11-10T15:21:18Z'
    mac: ENC[AES256_GCM,data:SI6ER5IrA7WwhQYlTbuL57h2i4CniaDV9S066StqOv52HyHsTVqviaNMGvowViRq+7JCOLFsU1KWxi1x/YgSiCR16Zcbx4xETzhRO1Uhq7xd+OVPjhgDGmrPNrxZ0LmMa/QathIM0Fcmcc4e1LHwdm9dDQ4mMgpDB4JpzloUc50=,iv:11MVFW9YrOsEA+W/A94A9BBk8LK/jYXGjvbmiDYLznw=,tag:cFNquL53fKf3UYuGpUxzUQ==,type:str]
    pgp:
    -   created_at: '2021-11-10T15:21:17Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/XR5/0RLgSQie6Q7ACeuHOcli12TLCXFNHaYweq83YrpK
            T0O6MvSAoMckEv4qDl6n7IbvffuA8yiFDqaoTUQCloj2Kz5Kt7NSb17DfMCO63P/
            oIR8gNZdUUawj0q4+T11X6o8FnE+aSWaiOoIKkuZNVyxVPLA9zOx2eR4HtL0XYbZ
            P1q0PAWoHRUaOXt+7ju7u9giLEC7+giujQHy0hxcdNiztlH7+avMm0/oJaLcuObS
            3/c0jEAsnVoNhwUigzWH3rv7QfHqTw3Pv9WJSVIFyY+iNdkHmMrAOXxnWIpsAaNh
            O4SPKOMs3Gwqq4yRQkM23t4PTYSxgF3eZ9ociHXh49JeATPIIiVP7xAYc6o0OjOb
            pNhgBaEOpCqG9M4/frIuWbOJUtnP5szjcRPz8N+WrsQolzL8NxtdtWhVZ9rCvY2i
            i+hJKJdPTuC3tGFtPC25chLCDYZ3XDuczznExXI2tQ==
            =WULH
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls|secret)$
    version: 3.6.1
