---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nodejs-image-stream.yaml
  - stasis-reactor-image-stream.yaml
  - stasis-reactor-deployment-config.yaml
  - stasis-reactor-service.yaml
  - stasis-reactor-route.yaml
  - stasis-reactor-build-config.yaml

generators:
  - ./secret-generator.yaml
