---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: dh-docs-server
  name: nodejs-10-centos7
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/internaldatahub/nodejs-10-centos7
