---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: idh-superset

bases:
  - github.com/opendatahub-io-contrib/odh-contrib-manifests/superset/base?ref=b0d11d452ce1a3a14d9c604a34c5d213342fb9aa

patchesStrategicMerge:
  - ./superset-deployment.yaml

generators:
- ./secret-generator.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: superset-config-py
    behavior: merge
    files:
      - superset_additional_config.py

images:
  - name: quay.io/opendatahub/superset:1.5.0-ubi
    newName: quay.io/opendatahub/superset
    newTag: 1.5.2-ubi
