---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: idh-superset

bases:
  - github.com/opendatahub-io/odh-manifests/superset/base?ref=42c1a674900b38a002a5c6c43904abfa582ef072

patchesStrategicMerge:
  - ./superset-deployment.yaml

generators:
- ./secret-generator.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: superset-config-py
    behavior: merge
    files:
      - superset_additional_config.py
