---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: idh-superset

bases:
  - github.com/opendatahub-io/odh-manifests/superset/base?ref=547d1a4ebfbcbae7e1fe005c5531be5cfe51dba7

patchesStrategicMerge:
  - superset-config-secret.yaml
