---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: idh-superset

bases:
  - github.com/opendatahub-io/odh-manifests/superset/base?ref=2aeb0165372a2b87a7c97ddb37462c8ff40f4185

patchesStrategicMerge:
  - ./superset-deployment.yaml

generators:
- ./secret-generator.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: superset-config-py
    behavior: merge
    files:
      - superset_additional_config.py
