---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: idh-superset

bases:
  - github.com/opendatahub-io/odh-manifests/superset/base?ref=c4d94c3308e6555715dcadf6461115c926724253

patchesStrategicMerge:
  - ./superset-deployment.yaml

generators:
- ./secret-generator.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: superset-config-py
    behavior: merge
    files:
      - superset_additional_config.py
