---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: idh-superset

bases:
  - github.com/opendatahub-io/odh-manifests/superset/base?ref=7ccd139de25ac9499307ab2534778107865c374c

patchesStrategicMerge:
  - superset-config-secret.yaml
