---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: idh-superset

bases:
  - github.com/opendatahub-io/odh-manifests/superset/base?ref=8f9691614ca9c2b436544b60d6603c82b0871cb6

patchesStrategicMerge:
  - ./superset-deployment.yaml

generators:
- ./secret-generator.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: superset-config-py
    behavior: merge
    files:
      - superset_additional_config.py

images:
  - name: quay.io/opendatahub/superset:1.4.1-ubi
    newName: quay.io/opendatahub/superset
    newTag: 1.5.2-ubi
