apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  template:
    spec:
      containers:
      - name: superset
        volumeMounts:
          - mountPath: "/etc/certs"
            name: trino-route-certificate-secret
            readOnly: true
      volumes:
        - name: trino-route-certificate-secret
          secret:
            secretName: trino-route-certificate-secret
