apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: s3-sync-tower-analytics-stage-
  name: s3-sync-tower-analytics-stage
spec:
  schedule: "0 H * * *"
  concurrencyPolicy: "Replace"
  workflowSpec:
    arguments:
      parameters:
        - name: sync_config
          value: tower-analytics-stage-sync
        - name: src_bucket
          value: tower-analytics-dbdumps-stage-s3
        - name: dest_bucket
          value: DH-DEV-TOWER-ANALYTICS
    workflowTemplateRef:
      name: s3-backup
