apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: s3-sync-cost-management-
  name: s3-sync-cost-management
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Replace"
  workflowSpec:
    arguments:
      parameters:
        - name: sync_config
          value: cost-management-sync
        - name: src_bucket
          value: hccm-prod-s3
        - name: dest_bucket
          value: DH-SECURE-COST-MANAGEMENT
        - name: alerts_to
          value: chambrid@redhat.com
    workflowTemplateRef:
      name: s3-backup
