apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: s3-sync-marketplace2ibm-
  name: s3-sync-marketplace2ibm
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Replace"
  workflowSpec:
    arguments:
      parameters:
        - name: sync_config
          value: marketplace2ibm-sync
        - name: src_bucket
          value: open-marketplace-prod
        - name: dest_bucket
          value: rhm-metering-cos-bucket
        - name: alerts_to
          value: data-hub-alerts@redhat.com
    workflowTemplateRef:
      name: s3-backup
