apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: s3-sync-tower-analytics-
  name: s3-sync-tower-analytics
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Replace"
  workflowSpec:
    arguments:
      parameters:
        - name: sync_config
          value: tower-analytics-sync
        - name: src_bucket
          value: tower-analytics-dbdumps-prod
        - name: dest_bucket
          value: DH-SECURE-TOWER-ANALYTICS
    workflowTemplateRef:
      name: s3-backup
