apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: s3-sync-rhods-usage-metrics-
  name: s3-sync-rhods-usage-metrics
spec:
  schedule: "0 5 * * *"
  concurrencyPolicy: "Replace"
  workflowSpec:
    arguments:
      parameters:
        - name: sync_config
          value: rhods-usage-metrics-sync
        - name: src_bucket
          value: rhods-external-usage-metrics
        - name: dest_bucket
          value: DH-SECURE-RHODS-USAGE-METRICS
    workflowTemplateRef:
      name: s3-backup
