apiVersion: v1
kind: Secret
metadata:
    labels:
        app: s3-backup-util
        template: s3-backup-util
    name: s3-backup-util-secrets
stringData:
    rclone.conf: ENC[AES256_GCM,data:eiM6P4zOdhH5NnpCi+sRmL3BSrjk6uwfzsk2jjk5P802Bbty/uwzVKdbnVKJ8NvNJ6+Q7Nhp0o+mgG5GpqYwQ97WAUpSvQlDIOet0CzehIRJ6SkZFTskWxHUPOwMgJjg2YlmpqcRb/7V/jmNedFFhZECEURDHPuJ36+cgqqyVDvOvL8h7khtc9LxzgZmYvBZbMt1QfJrOF85iBWtTNxx25Fy7Jv7LRSEkOihcZViVcdI7xRH/8xYJvR9kUvGfLUV0aj6ag2pLOPh5fuSXUVkz8gD+/+fCY7zibdk09jx77yOXbXyclbLfybz4+1JFRGaJ6gc+aOGCfU3HIr0Qsekdv2vDq2qncsuj7xNVSmmwifeqDCWivR1Busk4g6xX2Tdmf4RRV6hRAyxHLVhod96knEmrUDEiT8HaVESB6wpAx82ThSjgHe1/LD5KW8vfueoITor+RdbhTsPUjgyAguLWbr6zA/i/6H6+ua9URdMSYFNGJWMdn1Esc/Ba7Ggi66fsPwqES5nT7bssppg9GY+x1DW+1Cs59sVVhHtH3HfOB590Dt07eA4EBLFO14P3b0hhzhXIfx5Mzdt1IUgfLBKdRJ0itK03AmOmaL7j9RgFMNK0THbzeuTegzZmJhbbZ6gmvtLF7ABo2C7EIJbozxHUMM00fGV15rCgzodIVuf0mI9Lx4UwwomFwSeFO6eSvsFlPAPomUEn94lkrSf7ZjVmM9BJB1ctsJiLPvDha4DAtNat6dmCPaCS5qsb1drdL/Ijo/NUfRCQjRQ5h9L2mcZ0R7zWkjWihV7KvMMbiy7Ot1muBrGZK7sWdQYqWTrNyAxd/8C3OohzrFuOTA2gMNHfz/P4VJYnBuMz2m9BOUA0jrWdWDkymd42EEy4haiz1GT8LCvcWjrv1ZTB9UI3VEVy7R6EluzK31gO4UPBJj8PIbEB5KojlZmeOV06Qebi6tNZsT+NFa4AMJlTDya1Wbk6tKjku/GkIOBwHLe/ffxZAcpIo+GMtaPtnmPsivGjMknIvXJWUiO8VSGXVprc8B/XKv9ydFqi2iJuHUoHff7B+5ck1s+coKNTH7/qPOVSyLB809TnuUxeWXrNK+IGSrOrEP+tNyqoKDeNNMDHJuVT71P0/24jeyE5Go/drzVcbtEmjHzGQ==,iv:qgVHTmozEbNvPYFdZ30tWeRV9Llj2ZpjaVRtI4YHi/o=,tag:xzx/uRIrNKD2uLy5vaI02Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-05-03T13:23:03Z'
    mac: ENC[AES256_GCM,data:BUAqDDYG0YtSltuuUlhiC+OKW4uBkGheH7bozu3kpPLz+zVJtCSQKH8CyrOLMZYFaKU+J0TcrGMRUVPzz7rdc2UPvggmfWsHnulsFW3Nljwgv/iaVYRWq0pLcpZb6xPmhmBVPKLmdzvatElvJxzWktAnSETBUkXqC59fHcRCels=,iv:KhDxcYT9pXz/qK0WMkPonD/9XA5UuXPRI8XnW/Mg5z0=,tag:0zFivICYfzWZeYHNU2QzlQ==,type:str]
    pgp:
    -   created_at: '2022-02-07T18:20:57Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf8DcvxkCQZX4kLJGfKQ2ydyJ5P+3CDSzd4LQTUQNDqzkvo
            PttM2fvrCFZQexzzkRYD6SXOhUykw2LU0cpAI+hT2ToRIO2jAOvC+TZ/zLVi/c6S
            F6dpvt2KXnMK5K10sLZQQQJ3O0ZQPOzEUClFkwFKC1bRSvL/j2kD/qfFWUiPIZkc
            AS7OpRXvdZoct+9d9rV11gccNDOmTbqTktai0GF5U67wp0YrmhDV1ooi2+kGSACO
            rpF1Q6mo64O8JB1DqnlEjxPGovf/SFxEsIxVck07+yZUSw/gn3OH4NuIZfEdjN8B
            0FsZENhj6AhSxnsGy9hP11DNi80ikHEe2pq/0/tXd9JeAcOFWjf08ansLQU3mabZ
            D6CycfMi1006tYF70FQtBgRyaWHIE047korKQzApWOZvygTK+06ciW2MzlL6YHZI
            vcyCcAMv4kPEi+vFpyEPXckH/3EcWLdOf//sPlE5ag==
            =v8fH
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
