apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alert-template.yaml
  - s3-backup-workflow-template.yaml
  - ./backup-cron-workflows

generators:
  - secrets/secret-generator.yaml
