modules:
  http_2xx:
    prober: http
    timeout: 30s
    http:
      valid_status_codes: [200, 201, 202, 203, 204, 205, 206, 207, 208, 403]
      preferred_ip_protocol: "ip4"
  tcp_ingest:
    prober: tcp
    timeout: 15s
    http:
      preferred_ip_protocol: "ip4"
