---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blackbox.yaml
  - service.yaml
configMapGenerator:
  - name: blackbox-prober-config
    files:
    - blackbox-prober-config.yaml
generatorOptions:
  disableNameSuffixHash: true
