apiVersion: v1
kind: Secret
metadata:
    name: kafka-truststore
data:
    keystore.jks: ENC[AES256_GCM,data:/nhdwZimg0jcMrxwejZU9HJkD4zK+d9/4Vz0nsFYikpG463/cu9jG03xLX6h5NK6JyENW2EzwhrcjVVDg/pjyt4KNTKTIwelg4ErHaAaOsntz54lkSB+5ojOQ9xoHu7L9NQdNJriNO8rgyOPtBYeQHCT/JWNlFsxH4wOIG+NjuWYtHAkCMi8i0MlkwddVT286akP71CTefrPRGWLIRgsTUNBDoXy+MPAgHzkEU/BnyNpFeeA14OFC8kjmd3TqTqreH1Hc2C+9ePwpvuVC+sI8w6uWuuB+gHQTfSxzah6aigPfgk7rE3KIQbGZMyBRqAlkDo/+dyN6agYIYx2Dt7hEf4St8J3B1yRuvOUbntTfJWe4tAVPFtRX7/+R8eKR0l+hSkV109rxAbLAcXtL+Esb4UMKkQ3UKRiGPOJt7yqbnCq5z/RXut5O7pYeZZFDzitRrWU1mAHMiy/uI0dNVZY8WBm71L5Fose9KkbMXHTjbtzwgmPVZ/bYZ2xrgBDWnNGvCH2zKoZjPU6mHM7rBVuflWEXq8NrgB008wF91rFlICE9x+tSTdO899SDregcYyb7FBNsLhlVzTwrqS7ULYKw83fdX3KX43iFM4GIs/ro29kwds5egpphmuuuIsU9OjuRQAys8+TNdgyi1Hq0+pQFV62iNXz0kCmL3jKcW0qcAWhWe6ANv5yGPaZIK+ucVmn2ETQL272Nx2LDRufYYY6sKXihI+z+vl8DkAhameAa90/Lii1FcCB8kF/Fa3LFn2WcMMHKFtZWEuiEs84JSBr/56XhL09oJwFEtloNHtIYmgWioHcRlIYWqDKhqJhwTFEXoLOD6OjDCL117P+Dm3/rdHZqlNdlS9I5PxAJgot8HbiPXLZHq5OUDHTi3jrWTC2lPKlubSMtsseb/kv1cokau7pCHCAZxftckjAkCdY0Y1bV3F0X9BY/+npqh3Qgn7xIx+rgdbaDeNtj6NwZVpAqrq1AssH3l69g2v3OahrMGcCS+zQhBGacyKBVfTpqXOapEPvh/ptYJwrvRbnZUJ1J41hMAv8PW+cMKrpP5RwfP9EHGBpVe5UxDDCB71Vj+tmukLPslSYGcniRjoHkGhxbhUURTOHlv8t46sGpgqcT5DOMGBXkpLO35O+7Ok9CVBuxyqS2AvcbH0ld1kl/Z18+W6W0u3k/RM0Pv2ldvIG/1TjUjAl/nerUoEHW2y70L+KXXwazts9npa2/Rc7H01wqIkb6vf6/XPYqK63k5089gihyOFHLtJ7mGk3EGSZ+UPg3KDqpxmHyoZIZcN4VL1xZvoJIa0ZtW0H34qwJspJIgyaMLsfxaB+v4qPVYefOXIXFiF5YrDMQDmACWqRmK+uUeqzPkiskAo/PzaMFArdmuonQyjp/rR6YVDqvzRJIJi47RnpX29vCJNJrGGqmXSRF121HnHnFXD5j8IV6m1DM5uI6Cw8rse/t+9803C67X2T3HmLpJvzSgIp9plnTUG5mOHrM0kIub+q7hLehF9Ul9crBfV42gS3b2YdZr9cmEvd7ppC3BxeHVGq0yg0N3FgM9eoibfyZcZ1EwxXjNJ1itK2P7f7TIRm/nR7ArQZcBFyq85F2H3XsU7vzFvUBTaPfZLGGtN9vPIYhK4cTPC2Zo+EhQp1RpeahinKbtwkm6VV9TaQMCOStZks8EzO8HCTglXpFMXFA4TVdWMxNgfLHhksUrwr9SZs8DA5KWiewJotiFJ8lYWDNv1jyjjpqltyseRpIDF1BMSJFxRX+w015GRRbhjsmoha9ZgA7JX6vB14Z43xjbGq9Q0mCLonme4eraIAY1iK724BAk2PpjsUIsc623Mvh+xJ53DbP+6WU8WFporLdl49cK3rJxszJ7J55A13DTQ6KxvmsxFHzE15t1uLJ8lDaEYoXb+zcmSXGyujsv43N8dLdCCY4oetFmuOoo9h0RPAWoLmJsOFhchrcYx6IAVZ,iv:a3dbUzJ+rhu7GnbqkF9VsRmddbt2i16iHk0otTFrNjE=,tag:Zi1JsNhkzqUr8Q78Ck/1aQ==,type:str]
    SSL_KEYSTORE_PASSWORD: ENC[AES256_GCM,data:Ey+UHp0nmSOmCegr,iv:Rkj+TVQmTzQt1BcDXBT2RQcdsHc3C5ipC1Ny+Vl47es=,tag:e0F8qkVjZnGYTw7jPJ/n2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-18T18:37:23Z'
    mac: ENC[AES256_GCM,data:oAv0zC7VqBT495PnfENSJpPksfpJeBkC81N0pcT8TPuBuFSbtrYdKxT0V90moYDWmb5JI//1NY7TzllGV3vxBMZN+0mphs4KGH/5hP8TrpXklUQdQ1Svy14VnOnuKqkERTBXJDquNAhAm3fZH8vQtRb6yT3BGhKOU7cx910sAUI=,iv:SBZCH62eSz1k2Y2SaTjnjJ5kzzxWPirT8bY6ur+v6b0=,tag:9l2RGZ4lB5Lv9wqVSv867g==,type:str]
    pgp:
    -   created_at: '2021-03-18T18:37:23Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgAp0IBapnuyBFyI/iDs79QADdtl4amEbCgWUoFjRF6O9cv
            cNe/CRyihRw4D6jP/FlGY3W0FJUpTlrBdstobNfIdJ0nRhpbn1WY97Lmpxpd7Ma+
            dPwu2lopfMV9u9ZbWcOl1uIrv7fY+HFooDBebEQbAVCmJeNPU2/3xv4i/FAuPiaC
            Y8732c92DuO8kt+jIU3geEJchZd7UOP2Cbi7v78ehTww7vDzxC+2Jxt682oJdT3X
            gaS09Ruf2doS1c0GbBB7pBTW3fyZhJucBZ+r0Q1TmcxuP3TRsvkDdYfJi19aAxDU
            kvHh3MQEmZY2a7C6klVh1+piunOnFUroaA6icWPCEtJeAflcbKKrzvHpMJCQ70ig
            rNNdcFAfB3zKqLAItrwhWzjT6hsUfFfRG34PYMTaHekl8sR0WmfnprJLsyVydg9U
            oNpA3qwkzj88goOEsiqTo6s3R3nSpPY4NJdzLwvG8g==
            =76ni
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
