apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: "three"
spec:
  kafkaExporter: {}
  kafka:
    template:
      pod:
        tolerations: null
        affinity: null
    replicas: 3
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      min.insync.replicas: 2
      default.replication.factor: 3

    storage:
      size: "5Gi"
      class: "standard"
  zookeeper:
    replicas: 3
    storage:
      size: "5Gi"
      class: "standard"
