---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-prod-camel-k

resources:
  - ../../base

generators:
  - secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
