---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
files:
  - ./secrets/kafka2trino-truststore.enc.yaml
  - ./secrets/kafka-properties.enc.yaml
  - ./secrets/trino-beans.enc.yaml
