---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - data-foundation-pms-serviceaccount.yaml

generators:
  - ./secret-generator.yaml

namespace: internal-data-hub--telemetry-grafana-sandbox

patchesJson6902:
  - target:
      kind: DeploymentConfig
      name: grafana
      group: apps.openshift.io
      version: v1
    patch: |
      - op: replace
        path: /spec/template/spec/containers/1/env/1/value
        value: Editor
  - target:
      kind: ServiceMonitor
      name: telemetry-grafana-service-monitor
      group: monitoring.coreos.com
      version: v1
    patch: |
      - op: add
        path: /spec/namespaceSelector/matchNames/0
        value: dh-sandbox-telemetry-grafana
  - target:
      kind: RoleBinding
      name: telemeter-groups
      group: authorization.openshift.io
      version: v1
    patch: |
      - op: add
        path: /subjects/-
        value:
          kind: ServiceAccount
          name: data-foundation-pms
  - target:
      kind: DeploymentConfig
      group: apps.openshift.io
      version: v1
      name: grafana
    patch: |
      - op: add
        path: /spec/template/spec/containers/2/args/-
        value: --openshift-sar={"namespace":"dh-sandbox-telemetry-grafana","resource":"services","resourceName":"grafana","verb":"get"}
