---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - grafana-sandbox-route.yaml

generators:
  - ./secret-generator.yaml

namespace: dh-sandbox-telemetry-grafana

patchesJson6902:
  - target:
      kind: DeploymentConfig
      name: grafana
      group: apps.openshift.io
      version: v1
    patch: |
      - op: replace
        path: /spec/template/spec/containers/1/env/1/value
        value: Editor
