---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

generators:
  - ./secret-generator.yaml

namespace: dh-prod-telemetry-grafana

patchesJson6902:
  - target:
      kind: DeploymentConfig
      name: grafana
      group: apps.openshift.io
      version: v1
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
