---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

generators:
  - ./secret-generator.yaml

namespace: internal-data-hub--telemetry-grafana-prod

patchesJson6902:
  - patch: |
      - op: add
        path: "/spec/host"
        value: "grafana-internal-data-hub--telemetry-grafana-prod.apps.int.gpc.ocp-hub.prod.psi.redhat.com"
    target:
      kind: Route
      name: grafana
      version: v1
  - target:
      kind: DeploymentConfig
      name: grafana
      group: apps.openshift.io
      version: v1
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: ServiceMonitor
      name: telemetry-grafana-service-monitor
      group: monitoring.coreos.com
      version: v1
    patch: |
      - op: add
        path: /spec/namespaceSelector/matchNames/0
        value: dh-prod-telemetry-grafana
  - target:
      kind: DeploymentConfig
      group: apps.openshift.io
      version: v1
      name: grafana
    patch: |
      - op: add
        path: /spec/template/spec/containers/2/args/-
        value: --openshift-sar={"namespace":"internal-data-hub--telemetry-grafana-prod","resource":"services","resourceName":"grafana","verb":"get"}
