apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: s3webserver
    template: s3webserver
  name: s3webserver
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s3webserver:latest
  resources:
    limits:
      memory: 1Gi
  runPolicy: Serial
  source:
    git:
      uri: https://gitlab.cee.redhat.com/data-hub/s3-webserver.git
      ref: master
    type: Git
  strategy:
    type: "Docker"
    dockerStrategy:
      env:
        - name: GIT_SSL_NO_VERIFY
          value: 'true'
  triggers:
    - type: ConfigChange
