apiVersion: v1
kind: ConfigMap
metadata:
  name: cvp-webserver-s3webserver-config
  labels:
    template: s3webserver
data:
  s3webserver.config.yaml: |
    s3:
        access_key_env: AWS_ACCESS_KEY
        secret_key_env: AWS_SECRET_KEY
        endpoint_url: "https://s3.upshift.redhat.com/"
        buckets: ["DH-PROD-EXTERNAL-CI-DATA"]
        region: "us-east-1"
        root_prefix: ""
        prefix_delimiter: "/"
        default_bucket: "DH-PROD-EXTERNAL-CI-DATA"
    flask:
      host: 0.0.0.0
      port: 1337
