apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvp-webserver
  labels:
    app: cvp-webserver-s3webserver
    template: s3webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3webserver
      component: cvp-webserver-s3webserver
  template:
    metadata:
      name: s3webserver
      labels:
        app: s3webserver
        component: cvp-webserver-s3webserver
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: s3webserver
          imagePullPolicy: Always
          image: quay.io/internaldatahub/s3-webserver:latest
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: APP_SCRIPT
              value: /app/run.sh
            - name: CONFIG_FILE
              value: /etc/s3webserver/s3webserver.config.yaml
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cvp-webserver-s3webserver-secrets
                  key: s3-access-key
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cvp-webserver-s3webserver-secrets
                  key: s3-secret-key
          volumeMounts:
            - name: config
              mountPath: /etc/s3webserver
      volumes:
        - name: config
          configMap:
            name: cvp-webserver-s3webserver-config
