---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - imagestream.yaml
  - buildconfig.yaml
  - service.yaml
  - routes.yaml
  - deploymentconfig.yaml
  - configmap.yaml

generators:
  - ./secret-generator.yaml
