---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cvp-webserver
  annotations:
    haproxy.router.openshift.io/timeout: 10m
  labels:
    app: s3webserver
    template: s3webserver
    shard: internal
spec:
  host: cvp-webserver-internal-data-hub--s3-webserver-prod.apps.int.gpc.ocp-hub.prod.psi.redhat.com
  to:
    kind: Service
    name: cvp-webserver-s3webserver

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cvp-webserver-loadbalanced
  annotations:
    haproxy.router.openshift.io/timeout: 10m
  labels:
    app: s3webserver
    template: s3webserver
spec:
  host: external-ci-coldstorage.datahub.redhat.com
  to:
    kind: Service
    name: cvp-webserver-s3webserver
