apiVersion: v1
kind: Secret
metadata:
    name: cvp-webserver-s3webserver-secrets
    labels:
        template: s3webserver
type: Opaque
stringData:
    s3-access-key: ENC[AES256_GCM,data:XCAHWKdK5bWni5UUrOckyxHjBio=,iv:oBTKih8PXZhw8rIYf6dLVYMg6l9f1XbLf04PL0I6Mfk=,tag:CqEWuFEL0aaizOrwX5mrIQ==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:sJgYE1gEOUvWt2BXiKtAYnx4Z/ayw+2JhK1AbUq9Py4x/h2Ec7awqA==,iv:9j3jsJ8LyWq0isWDms/Y6kERdbCBFD3pU24PAUEVNo4=,tag:Qbto38o7f2UevwtjJlPH/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-03T13:31:16Z"
    mac: ENC[AES256_GCM,data:Jkw/gk2nDzp806Sc5xaqMLwbd2MadtyLndeNDDfVLY0judsBZTbkYp1AtrU49HEu8Ibv4IIb7FS8d6G3SYQpq04qSOj0ZhE4HMeeD7Y6HENuumxGrbTipVM78NA/l2jTemT33YLRLehkLdyjg4WFhLt3vi5kuRaIMZvBGA25IHw=,iv:ANmD0xf545WheA1RAduqd1WjEIcWp3RKEomqU1oSYio=,tag:cn54Fp5W/d3+QoHJRd2SOw==,type:str]
    pgp:
        - created_at: "2022-02-11T14:14:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgAiLu/GfvFWjJlXlpyXxOLY9Zzz9IHIybZOthreqT/5J62
            0/UJGlL0UDWDCsGQzVO1gesxymC9T8Nnxf2nHUEWvvXn6JIX/uHUAVNIKJghEVfb
            M4cWXxgwzAtnG7Xq01vhvBG6kVBmTsdytVTR3CHiONWeGR90XiGl4a4r15Y0MKbo
            dhUNZuhknc5R4BfUOVLVVJD306HqWs6xZOlCVHkjDyWiK7d4j3POdbGJ76h8nkCu
            7rRxpJ21cJDwY/3yPc8UZvw9LQ65xKc28D/FvsJndX2snonQZwz+ayv4Yr/iJwnN
            +r9xZHcozWWuyH8h+Nrb4EHG/qVfVym1ephhlqcJydJeAaX2fryWIibVHJeoSXjr
            5uOGiTMdi7opQDLLzT9VoJqJSPb/Yuq5QTeJdTfz+HJujtTTeOMyvAFtR5TBDNb2
            dNatFqDtSVPifBsJs9sNS4vZGgmN/hxJYfcfu3q3ng==
            =vVSv
            -----END PGP MESSAGE-----
          fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.7.1
