apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: addon-managed-odh
  namespace: redhat-ods-operator
spec:
  channel: beta
  name: managed-odh
  source: addon-managed-odh-catalog
  sourceNamespace: openshift-marketplace
