---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-prod-message-bus

resources:
  - ../../../base/kafka
  - ./kafka-topics.yaml

patchesStrategicMerge:
  - ./kafka-cluster.yaml
