apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
    name: grafana-datasource
    namespace: dh-prod-monitoring
spec:
    datasources:
    -   editable: false
        jsonData:
            httpHeaderName1: Authorization
            timeInterval: 5s
            tlsSkipVerify: true
        name: prod-data-hub
        secureJsonData:
            httpHeaderValue1: ENC[AES256_GCM,data:4Wz0ayaOgypAUuzn/J2wHr/6KX6K9a4M8JYHTYmWQsK8Hnq4NZ43G2s42yAaFvTCEgEEx7NVXCL32lTI25lNSq/lu9+Sj60wCzARKE+bk9nu5DGozKQ7ia0Kh/b/jtN9WgIeRvVHncyZ8btJLYYps+T6diZF+f3/Sp1sjbkMXUr1m79ArH2uLgXuzAZXFhd2zs8u3wgkLn+kPUoDCiCC6vMYzngPJpM9/ZXpu9XIC8jmLQ8VViAGBKj/8mPEoKByOmECNehw2mEUQjUTzG+pwH2gs06hLSK/sK/SH+Hk4Do6FNY5iTAEKkxUb5Yeqn+MwfZEGz+/X9i7yVJVdSlvw2UNNC6uudsS0qqeTyvYwTnSJQBdaO2yoa0S3rhIh3qE6GB4kE8yClDhhKjRcx6aZmdN9LBJ4Yy+YA+l+3O/KxC8KmblwwzFIR3J+++TOAw6Oirm/ITNuxCNFeZCkqjF8AlHA7OqBmIVI32xCfVLJN3jl/XxvFQtD064iZNid+V3+GPsFc+C9QzDI4WWaBryw1BqImZYGM9KFL8yI/eQbJy+UTvCV/zomnouKbDNIgF7zESm6qSC9EjsrjXwuH3498sF3gSzdc5M8hioV48lc2vbSSKnFWkFrna3GWqMDumgNLUz3LdYYF4bwy8CGCqZYewGjggHB3WHVc3GnPlqkQ2v7dhaF/VAwOtz0zUo5/6ZFlDOZZ7l6aT5Pe2IF3knMSilIpJl6MHudVnBYZwE/Zceh6aYC6y6OmKWFMr1YlGOBEYQzEf+AyIvMqfhx/FurFkgFTG0TpmAYoJmbIP4sv/KTUdWPxS0XgtPr6AnPTcmO4zl3bKqJtceDAoJL1BRhOvDpd51ovWghmMb4s1o1QkvbsKvz3ZBI4nEav7g4TlJ9bJbRnpHpMq8o3Yqnixv2YKnZh8L6jV/QwTfxkUDkwzdTB0wzUp4hhf+6lbuN1TEdh46g5Ft4Pk9Clgpb1ET6RCEhegrJ2tWa5dYJRXIWu0bDEotFOGeUsEK1Ez9Sa+ozrClyk3oHjGyIM0NnYCg/D8Uu4iG7ilVfaRgr+S23ApZO6C8RRUbcHUR/9khAGRrkdMxfXo1w88Sqr18f3Y5L300KxS2E+cEyqG8rfg8AuR+aKr2/OlZKUXnMwYrnRu5Bd5CNhYeHTuH1Ju321WnwmBh2Sf/MMB8vpJaOeaM3qHo89OaTPlvrFP4IgCwhmXkTYBIB0B3Ik02qCC3pWGZcpnq48LVBX3o7vo2kyZHycPryXvVAIZJlZRvl+lNMcCkmqwQyLuGVnwOeIG3Il5YSnDRdxB9WN3+AIZcMoAo3LUUog8kytRdMWflCrK86PbqMGlsB5QD1spLkELNehQ/Yq7n90ceRRSuh8n2Vq+x4VnL82XKIp3FMPpyL2aCZhVJGvZabP7OygztjubwF7q9N5YqmF2BEiMptQ61UdunpI40OMDt/4T9IdpVuLXIGuLmnmfQLbM9MWyUfVd6Oe3p7rDyU5IIIYZ925na8S0G1SPZr0TssPQa5fBgwiqUOWHahTFFfHxnZF3C82aEfg1t5OP3MDUo0gk9QkG7986rScvyCwQoKSgOZXiN/Iutd4eB765+wTSweSOW9ThRJamX1ql96AwkIIJ31VcvyAw35CtJXKf79/AH/hm/8xp5ziwbblDfLtedVbZ21+nNVOWqBiAkb2Xne/HoaJPaft9DTMFzHgMnF9eKkMOmB6US4yYo30gQ/5nTJHeF5NPgKMNByziv7lQ1gATuD9CDmFKdUVoEWdoeDzE5K7GDxhTJd8cx0vwfnrBaB15MgiuKRSzrEFa8WR63NjqrLQzDHZ1kCK9x+F8hggOCEjVSjV4=,iv:Tlr09ydShSHErHVB1dLJfUTtPZugimFoXANHUkMgqI4=,tag:aYDeUum/6ZV7oHTW8zJ4Tw==,type:str]
        type: prometheus
        url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    name: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-02-07T19:54:27Z'
    mac: ENC[AES256_GCM,data:kcez34ygXARqN1TTta2c0/IU1wYIQUVdJHe0Yz6eQkXZNiVHzPeAbQjEJRgLqtmWGKVzsMC04eSzuOg2X5jiI5vJl+453yMcPAKr9NdcZqSQvJ7+/fD1lcPPUFjL51iCTfDTaIOWzotGJTHbuD6T7sW/GXidFPXlNdUuT24GwXA=,iv:NB+oyfhtX3zjQZ9bluJ9Jh2rpF1IxcsUto7P6w2uFDA=,tag:Uz5S+/psLlCUKsSg6EV0uA==,type:str]
    pgp:
    -   created_at: '2022-02-07T19:54:26Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+NOWABN0gTwOzWSuqwyk23GUFK6hJclk76RddhIOQ0N/c
            2AD9iA6vxQXVVktzeFF2gS06so3znHfYWGs8zrRAHxmwAe/hxPlpubgXQAqKHaTE
            w3yGVZg6pGEcxD09DcIU5VBqqzV2OezJeZI2+mwfQdywvpkQWBeJc4PvxYRXbC7+
            CeFjoFnsmAI0j5+oV+MxGCjS0vtnNoulOjks9Cv2seTglOdBmHZUv3q8VY+WBkgu
            g8VnI6Wxmk5qqQNIAm8e4S7x9NZSpx98J+tDb8lmAEWeC0ZjptfTluwxH/HlaSjc
            t4reLWqliWAogprfm+nP4q/5dloVG+O/YZ5lM/L+GtJeAVoBFc0wDiPhZ/lLXpzO
            UfLATA3jNatU/9ocGd6CNjDB6d6zN1w+HFn9lN3M+TLK/jdoezBnzdxZDAh70E4Q
            +HkXo9H6v34C66FX0HfFEguURpX/K6/tM9v0TYbUbg==
            =ou9Q
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|basicAuthPassword|admin_password|httpHeaderValue1)$
    version: 3.5.0
