apiVersion: batch/v1
kind: CronJob
metadata:
  name: trino-partition-updater
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger
            image: quay.io/rhn_support_sreber/curl
            args: ["curl", "-X", "POST", "--data", "{}", "el-trino-partition-updater:8080"]
          restartPolicy: Never
