apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trino-partition-updater
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: "trino-partition-updater-"
      spec:
        timeout: 10h0m0s
        pipelineRef:
          name: trino-partition-updater
        workspaces:
          - name: tables-list
            persistentVolumeClaim:
              claimName: tables-list-pvc
