apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: trino-partition-updater
spec:
  tasks:
    - name: get-all-partitioned-tables
      taskRef:
        name: get-all-partitioned-tables
    - name: update-partition-metadata
      timeout: 10h0m0s
      taskRef:
        name: update-partition-metadata
      params:
        - name: tables_list
          value: $(tasks.get-all-partitioned-tables.results.tables-list)
