---
apiVersion: v1
kind: Secret
metadata:
  name: trino-config
stringData:
  config-coordinator.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080
    http-server.authentication.type=PASSWORD
    http-server.process-forwarded=true
    password-authenticator.config-files=/etc/trino/ldap-authenticator.properties,/etc/trino/file-authenticator.properties
    query.max-memory-per-node=0.25
    query.max-total-memory-per-node=0.5
    query.max-memory=1.0
  config-worker.properties: |-
    coordinator=false
    http-server.http.port=8080
    discovery.uri=http://trino-service:8080
    query.max-memory-per-node=0.25
    query.max-total-memory-per-node=0.5
    query.max-memory=1.0
