apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "dh-dev-argo"

resources:
  - ../../base/

generators:
  - secrets/secret-generator.yaml

patchesJson6902:
  - path: s3-backup-pipeline-cron-workflows.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: CronWorkflow
      name: s3-backup-pipeline-cron-workflows
