---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supersetdb-data
  labels:
    app: supersetdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    limits:
      storage: 10Gi
