---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supersetdb-data
  annotations:
    value:
      volume.beta.kubernetes.io/storage-class: "ceph-dyn-data-hub-stage"
  labels:
    app: supersetdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
