apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
    name: grafana
spec:
    baseImage: quay.io/app-sre/grafana:7.1.1
    client:
        preferService: true
    config:
        auth.anonymous:
            enabled: false
        auth.ldap:
            config_file: /etc/grafana-configmaps/ldap-config/ldap.toml
            enabled: true
        log:
            level: warn
            mode: console
    deployment:
        skipCreateAdminAccount: true
        envFrom:
        - secretRef:
              name: admin-credentials
    dashboardLabelSelector:
    -   matchExpressions:
        -   key: app
            operator: In
            values:
            - grafana
    ingress:
        enabled: true
    secrets:
    - default-ingress-cert
    configMaps:
    - ldap-config
