apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
    name: grafana
spec:
    baseImage: quay.io/app-sre/grafana:7.1.1
    client:
        preferService: true
    config:
        auth.anonymous:
            enabled: false
        auth.ldap:
            config_file: /etc/grafana-configmaps/ldap-config/ldap.toml
            enabled: true
        log:
            level: warn
            mode: console
    deployment:
        skipCreateAdminAccount: true
        envFrom:
        - secretRef:
              name: admin-credentials
    dashboardLabelSelector:
    -   matchExpressions:
        -   key: app
            operator: In
            values:
            - grafana
    containers:
    -   args:
        - -provider=openshift
        - -pass-basic-auth=false
        - -https-address=:9091
        - -http-address=
        - -email-domain=*
        - -upstream=http://localhost:3000
        - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
        - -openshift-service-account=grafana-serviceaccount
        - -openshift-ca=/etc/pki/tls/cert.pem
        - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - -openshift-ca=/etc/pki/router-ca/ca-bundle.crt
        - -tls-cert=/etc/tls/private/tls.crt
        - -tls-key=/etc/tls/private/tls.key
        - -cookie-secret-file=/etc/proxy/secrets/session_secret
        - -skip-auth-regex=^/metrics,/api/datasources,/api/dashboards
        - '-openshift-sar={"resource": "namespaces", "verb": "get", "resourceName":
            "dh-psi-monitoring", "namespace": "dh-psi-monitoring"}'
        image: registry.redhat.io/openshift4/ose-oauth-proxy:v4.4
        name: oauth-proxy
        ports:
        -   containerPort: 9091
            name: oauth-proxy
        resources: {}
        volumeMounts:
        -   mountPath: /etc/tls/private
            name: secret-grafana-tls
            readOnly: false
        -   mountPath: /etc/proxy/secrets
            name: secret-grafana-proxy
            readOnly: false
        -   mountPath: /etc/pki/router-ca
            name: secret-default-ingress-cert
            readOnly: true
    ingress:
        enabled: true
        targetPort: oauth-proxy
        termination: reencrypt
    secrets:
    - grafana-tls
    - grafana-proxy
    - default-ingress-cert
    configMaps:
    - ldap-config
    service:
        annotations:
            service.alpha.openshift.io/serving-cert-secret-name: grafana-tls
        ports:
        -   name: oauth-proxy
            port: 9091
            protocol: TCP
            targetPort: oauth-proxy
    serviceAccount:
        annotations:
            serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-route"}}'
