---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-psi-monitoring
resources:
  - grafana.yaml
  - dashboards
generators:
  - secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - files:
      - configs/ldap.toml
    name: ldap-config
