---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
files:
  - ./secrets/proxy_secret_grafana.enc.yaml
  - ./secrets/router-ca.enc.yaml
  - ./datasources/datasource.yaml
  - ./grafana.yaml
