apiVersion: v1
kind: Secret
metadata:
    labels:
        app: bareos-fd
    name: bareos-fd-config
data:
    bareos-fd.conf: ENC[AES256_GCM,data:0WqwE2C1KLzIIrJLCfe6Jg9MHh3Sm0uRA+lRuzYGDvkxrAGfNs3RwtgD7KD8Kn64TKuAJrMIXK5jaEZ5x4Pl26TH0x0G18kC4IpreqiIRsz99yxdyHEXSpCdR44JWGFtoNDu9RfkkCGACmDz/4GRK787LcGpYlDm+vm5y+koA6uK1dIbpWS9Rh/cEfhfXGuM0aaU2Pqvro5m19P+t/bjYF8SPBfSyHSKGR4YG7igjuBRyIEHVZQRrEZP/nJ2nyVQnN1WbS85cWPrQ7qDwXz2B2S7OTcSMlLpYGBJGhFNQnOreiUeCkoyHOjneoC+KGL3i8zddDeKUTD8RD1QArFzLHlIA1WvrdKujc8xCWKbUbF5qyTK3xs5JMfXX9OlToXWxZkX2rbovXu5prwS1AfgVld/yV6ZHg0UuhXwYCeVSouZozt1c5RFpEqP+Hn/jkRsH6pBdMPZtGPG04e7Dx1fG2tILKhJxZHAO3od,iv:8e5lm1xMEV360l6T42u7RfblBbM2egy/WBvG/3VvGo8=,tag:vY6TIKFoFNVGfL+AIZyorg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-01-14T15:05:20Z'
    mac: ENC[AES256_GCM,data:Dvx+KHA+/YRhmvbyKIfwWKft+M5Xjh7H+LFLXvHmXaz4+6PqfCHncVsi6X3EIQsiWm6C2wAvV4rLNkZFzRCHlpmLXTpbdRZJeqvdzXN+fISZKpkZACNXXxjCJ2KmEqAuJQnyzKpGMf3bqp4iY38+pFDPy5k9r+26QNnoj72P070=,iv:DQDMVufDB6TbbVT6Qfb0POwX8iR18rv40J9iVBTOxpM=,tag:J7IKtJoHLzW6zRoramb4BQ==,type:str]
    pgp:
    -   created_at: '2022-01-14T15:05:19Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/SOiulRXK5yd9SGqLCU/r+LN33/UH5F3hbHF9SpZQQTq4
            GJMoCZaht/jXdE+X+P4cKZm65YSaeXgOA310R+jRc5A9CH/h8I1n6CD4VqODpJ1P
            fJ4FBJZKt1bqUkkp7vdAOA4KBnrzoGokFYSimgOkBiApbCRDuXggnKX+j7BoIOBr
            TnVwGZ/puvMruqr8b965vHFrRfdp6CeGGEMS2yIqV8C/+M85iU813BlBISTMPlBL
            vTx1l3gbHyeetg6h/hfMmHqF3+lPnIGLb+6n5aU/xG6l3WiQ8aeuI+m1/yG5fb++
            qA8syWI8cOQsBMWy3ghPXWyO29+8n5f7AomAA9731dJeAcEOcWR1FOzUCAMj41jN
            mUsY3Y87NX1Hj0Q/SLnt56G4aScJyPDn/IvrBHE0IC2CmnafAKrYqua9f3PhJlOc
            KBfWRBKpYIStUpJS3NUncgAZe9EPA6dJUV5dAKAJIg==
            =QwSV
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
