apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: bareos-fd
  name: bareos-fd
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: docker-registry-default.cloud.registry.upshift.redhat.com/bareos/bareos-fd-psql:9.6
      referencePolicy:
        type: Source
