---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-prod-superset

resources:
  - ../../../base/superset
  - supersetdb-route.yaml

generators:
  - secret-generator.yaml

patchesJson6902:
  - patch: |
      - op: replace
        path: /data/superset_secret
        value: prod-superset
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_db_secret
        value: prod-supersetdb-secret
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_cpu_requests
        value: "1"
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_memory_requests
        value: 1Gi
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_cpu_limits
        value: "2"
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_memory_limits
        value: 2Gi
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_db_cpu_requests
        value: 1000m
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_db_memory_requests
        value: 1Gi
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_db_cpu_limits
        value: 2000m
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_db_memory_limits
        value: 2Gi
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /metadata/name
        value: postgresql
    target:
      kind: PersistentVolumeClaim
      name: supersetdb-data
      version: v1
  - patch: |
      - op: add
        path: "/spec/storageClassName"
        value: ceph-dyn-datahub-prod-psi
    target:
      kind: PersistentVolumeClaim
      name: postgresql
      version: v1
  - patch: |
      - op: add
        path: "/metadata/annotations"
        value:
          haproxy.router.openshift.io/timeout: 200s
    target:
      kind: Route
      name: superset
      version: v1

patchesStrategicMerge:
  - ./supersetdb-deployment-pvc-backup.yaml
  - ./supersetdb-service-nodePort.yaml
