kind: Secret
apiVersion: v1
metadata:
    name: redhat-rhods-pagerduty
    namespace: redhat-ods-monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
        kustomize.config.k8s.io/behavior: replace
stringData:
    PAGERDUTY_KEY: ENC[AES256_GCM,data:2vkn1FwQbg==,iv:zvHBDrWbikUnw9G06sy/e9BiwctqdnCEKaJLIQOsmig=,tag:N6ezsKWfAT0cSoMdtQH4dA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-10-12T19:28:31Z'
    mac: ENC[AES256_GCM,data:ypA3y482CMaIwbB+GuUsIQOJwNWLpbgkxU5vXChLP5H9Z5wMeZepBoi5ggo0tgBRMZxnXZ5s99UwrJN9/VNVs2GCiWZ0ImEXiL0FFD1QVEmM32ZND20z6TyYu6mBoPi0pnD0KACP/Bm1S6jDyNc52hgcUve4rvNAerJb89roNc8=,iv:pGJg1gnLxNf8mC75M1t12vEijmLw/ksjiaemnzuTNKI=,tag:+Q9zBme98t3te0A7kf+M3g==,type:str]
    pgp:
    -   created_at: '2021-10-12T19:23:29Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgApKZwJcpyNvg4cW9zn89/cKYJxhduVHk38vQ/NopjNNyf
            NFinGsaDii6kgwoASpjVRfB8uBod3FJCfmiBxpiGfhPKg2YFGKAWywZ2+NjUIrVK
            ciDSZ48aebfooEEX6Z/xxq0jvfqWwlZAxx2bmlPHcRZThoxHbHL0W2UF6O9SCB6Q
            jziPCbzAx9ZRhZmA/1NNxwjSq2zMq3oJ8L/L6RltUorsyz3/kT1GQXOikf/iI1yA
            poDnyrTAM0EAwSwBkCMKuO0Ze3gVcHQV/vXUpLaZdWyAD0kNPd3w/3B6HEXoUUBT
            FiW5FIfGK/dRldLqtwv0K5wASxtudULhED635Syii9JeAUeyHfWkdjtnPvc9L8Cj
            K93EPtIJy3pG415SQ/S+1CBgGoPBUrunzMIkhIXFs521Tcrff+ohkhrQPPYXm2f2
            H0tM5clGKrdullhdutJlT0QW7X45cqJm+B82i7N0kw==
            =e4Id
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
