---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - grafana-proxy-config-secret.yaml
  - grafana-cluster-role-binding.yaml

namespace: dh-dev-telemetry-grafana

patchesJson6902:
  - target:
      kind: ServiceMonitor
      name: telemetry-grafana-service-monitor
      group: monitoring.coreos.com
      version: v1
    patch: |
      - op: add
        path: /spec/namespaceSelector/matchNames/0
        value: dh-dev-telemetry-grafana
  - target:
      kind: DeploymentConfig
      group: apps.openshift.io
      version: v1
      name: grafana
    patch: |
      - op: add
        path: /spec/template/spec/containers/2/args/-
        value: --openshift-sar={"namespace":"dh-dev-telemetry-grafana","resource":"services","resourceName":"grafana","verb":"get"}
