apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: s3-sync
spec:
  params:
    - name: src_bucket
      type: string
    - name: dest_bucket
      type: string
    - name: rclone_params
      type: string
    - name: sync_config_secret_name
      type: string
  steps:
    - name: s3-sync
      image: quay.io/internaldatahub/rclone:latest
      timeout: 10h0m0s
      resources:
        limits:
          memory: 2Gi
      script: |
        set -x
        src_bucket="source:$(params.src_bucket)"
        dest_bucket="destination:$(params.dest_bucket)"
        extra_params="$(params.rclone_params)"
        echo "Creating Bucket $dest_bucket if it doesnt exit yet..."
        rclone --config /etc/s3-backup-util/rclone.conf mkdir --verbose ${dest_bucket}
        echo "RClone Copying from $src_bucket to $dest_bucket..."
        rclone --config /etc/s3-backup-util/rclone.conf copy --verbose ${extra_params} ${src_bucket} ${dest_bucket}
        echo "Rclone complete."
      volumeMounts:
        - mountPath: /etc/s3-backup-util
          name: sync-config
  volumes:
    - name: sync-config
      secret:
        secretName: "$(params.sync_config_secret_name)"
