apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: s3-sync-eventlistener-binding
subjects:
  - kind: ServiceAccount
    name: s3-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
