apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s3-sync
spec:
  params:
    - name: src_bucket
    - name: dest_bucket
    - name: rclone_params
      default: ""
    - name: sync_config_secret_name
  tasks:
    - name: s3-sync
      timeout: 10h0m0s
      taskRef:
        name: s3-sync
      params:
        - name: src_bucket
          value: "$(params.src_bucket)"
        - name: dest_bucket
          value: "$(params.dest_bucket)"
        - name: rclone_params
          value: "$(params.rclone_params)"
        - name: sync_config_secret_name
          value: "$(params.sync_config_secret_name)"
