apiVersion: v1
kind: Secret
metadata:
    name: kafka-cert
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:DmU+/ayEe+XmFC8vDu8exhAfYoahNjEGKW7gCocUG7QY9POlNcqOKP5AAW+LXHXQfxSYdV65yXCClzsV6rsj3rfXaZRV5BloxPDV1sdLkBAc2E/ZqQJu25KQFXnjTB8RYc6pXi8X1YA9oMADYh5K+PMx1A1Bxji3CTwKiCto26xFXBROMmERzZ/nSyClIGHYb7X591vx+s9tA270FoT8yyGK7PwouP3w/Q4A4j4Q3laNqMvG6JuJrZFqFEvVTEcTbFi8ZyXSQbCnU4FB8B0fMuwt824rkuwHUjjv+3nfCusy+1c2mVH3xXVnaAfM2PJXnOPeDPt7y2kMT3JQ7pEAXwgRilj6cRUqB65BGPB+e6JFb1+EgQg4f6ymlsvmWW02IoGJre7s3QkDmPBHcdOLf4jLiXIoqjWVaUb61/TqzhlvrLOO64D3kvJ79/4AiHPAFHyB5bkedb3WI5AKXbHmK3rR5qEJiBXMkUvrKIFpZcfPfCukYbmDKaJbaSTeLS/feRPZFWEA41BvKgyXWoBxa1UvdWMtiTZ4bQdMMFPSjJRzP8EJJd5Pw9Eb53ULYlVAZ3IOmLUbM/sioVASL9+pFt2ATZtDm7KBUImkUVlpktYWbtwl6nAAGuF5hHACdOlDUlaZ3W53Rm4AycZpm53B5j6dpPTcrNNMYu62TBQZaFO5EtVMNcBGAei1s93VRI5pAGQnBdVZxTbsKiPEoOurKgsAmnRwhvg/c7SQjUkLV8yeAdFTg1UjM2kzdTz0y4Ja8DoIppJclIZ/F0kcMXAHWZuSAeKqFY8JchVJp/vUwxddAq70s8Dxo2RDElgGg6+6P3CdbDNYCzw2XffSK8D6FYNRwNs4zHXSQd71okFnjQdKFvVJCjgSMRXoJrvBQo6+lV6Zxm0cV8lui0uC8GGF7izaaHsfs6RCleYqTpoNKF8t4bkbrx8JNwMqHvFpd5L9Ns14/7W1BDrCl6zJTYsd8oWpn7HdNSXNlDDvCDVX2fTjjJIrRk2Q72U1jG5urgIPEZRfubbpFcWHH+jV8conbQ6mzW+/BsfUThCH00BytmSIT7qx24xHaPztArbWgog1jA4U1qpkbPg05QQ+XVodq6PAcIgj9x8QLOOMOU29BtuG3+4U8eKrFZa0N8F+dtgbo1yq0skznd0tLJuLt3SLMLWWoVgnmtQg/fybK8e0ts+1hYy7npwSMGz2/KrFYNRTDieQJpmjFQ+Tanc18X+U9ASzOwB+ANPhpGKYMis/pR2+9FRqSFD+L/NTtDKrQgdobTuASPpELLyU0fZcJz6Sl1vbPYkJU9zC3ilMfRTgXN9HCr04e/oLVaZD47NdsSWx6K5aE+49IomblJV1jqxk4xli0adlzLyz0f1DYBB9XHb/SpZ1YuZ0mDV752mbvVTMmojqj7R2qxPDuCi1WG+1RYVhnS13IXEtX5/C0XLuTzcJSegLP95M246mmyj6eU4VfWc8sF+EWLfu2aEFVCcztATsB1gqm0FGOCCZpqF2hZR7lA1mTGp4RouroRnRNfsThodPlIObPiN8UDGw,iv:FFc0elA3Gsa0/4u0fhOBXZY49At1BDJohcEc7B2xCXk=,tag:gmFFVQSy4Etmtr/ZBw3fjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-01T14:32:18Z'
    mac: ENC[AES256_GCM,data:I8yjri/J0wjGD6gwmfhiI/glXnAL6kpWT2mgD+SSII6cch7bRB2IBWcNtJ5vT9ap8kRg5QBawVhxA9t4/6/Eb5bilqvAfNjdPvW9Oqn6IOY6hDGRHT9haZyzpki/GJs/CO5jNvzAgbuXwociTt+eJ1dGoOKvvdno6siyjVF1IVE=,iv:zs3kk2lNePqDombvFP8x+LxY4AkecFKLPchK9nV08sI=,tag:TP4DH1Bhm9i/X46bj67gKg==,type:str]
    pgp:
    -   created_at: '2020-09-18T20:39:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf/UmnVD+vvua3NgLH9NdmAbj9x+CeK2vRxtHMQWlsj3QA/
            YPeyLgV5UN3VQnkNMiIY62QrGNcAl5cT2A7OXWrcO/J3CN1Q/+ZkJ4s9EY/WHU+Z
            sPPtil3UpzwggrzXiPk7bq/fNuX8kamw3fYymu7fnXE6iWeuhgB+R+wgNomrWAkX
            RbpeoBLi18X3lD6TcomyTI85ukv/Y3r2MnLSV2ZR1JrMfXKq1Z/emrxLImaqirWe
            51hsTXZ9F0PbFUu6TLF7IJyNdkiFOyJ6P/1oU+09/8k4d0Rqodq+Bj/8xT8hbdVu
            b1VEsrSnNY3i2XBOrr18nxbWfgnoqjjsQcUfCHFnJtJeAa0IkTGiW0eINen7dqbZ
            o7fDXoyZB1AHG+yinbWgiSFk3lFSE1Ak+xe8zPNg2WTGf5NBiAhiIse4/HqvmymZ
            3ofo5RSLGmr7TQOnhkF943CR+gFGoJgrKuNXoiyirQ==
            =/4au
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
