---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: data-hub
  name: data-hub
  namespace: dh-psi-monitoring
spec:
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: additional-scrape-configs.yaml
  serviceAccountName: monitoring-sa
  listenLocal: true
  containers:
    - args:
        - '-provider=openshift'
        - '-https-address=:8443'
        - '-http-address='
        - '-email-domain=*'
        - '-upstream=http://localhost:9090'
        - '-htpasswd-file=/etc/proxy/htpasswd/auth/htpasswd'
        - '-openshift-service-account=monitoring-sa'
        - '-openshift-ca=/etc/pki/tls/cert.pem'
        - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
        - '-openshift-ca=/etc/pki/router-ca/ca-bundle.crt'
        - '-tls-cert=/etc/tls/private/tls.crt'
        - '-tls-key=/etc/tls/private/tls.key'
        - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
        - '-skip-auth-regex=^/metrics'
        - >-
          -openshift-sar={"resource": "namespaces", "verb": "get",
          "resourceName": "dh-psi-monitoring", "namespace": "dh-psi-monitoring"}
      image: 'registry.redhat.io/openshift4/ose-oauth-proxy:v4.4'
      imagePullPolicy: Always
      name: oauth-proxy
      ports:
        - containerPort: 8443
          name: web
      volumeMounts:
        - mountPath: /etc/tls/private
          name: prometheus-tls
        - mountPath: /etc/proxy/secrets
          name: prometheus-proxy
        - mountPath: /etc/pki/router-ca
          name: router-ca
          readOnly: true
        - mountPath: /etc/proxy/htpasswd/auth
          name: prometheus-htpasswd
  volumes:
    - name: prometheus-tls
      secret:
        secretName: prometheus-tls
    - name: prometheus-proxy
      secret:
        secretName: prometheus-proxy
    - name: router-ca
      secret:
        secretName: default-ingress-cert
    - name: prometheus-htpasswd
      secret:
        secretName: prometheus-htpasswd
