apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
    name: prometheus
spec:
    datasources:
    -   basicAuthUser: grafana
        access: proxy
        secureJsonData:
            basicAuthPassword: ENC[AES256_GCM,data:ngHDXHoCB1Lc,iv:D6Ng+ns+bhclQWi1AK3SoERO4dLg7iSFMVeks13NhoE=,tag:JJkAv2ad1aErEG692DfFkA==,type:str]
        name: prom-basic-auth
        url: https://prometheus-dh-psi-monitoring.apps.ocp4.prod.psi.redhat.com
        jsonData:
            timeInterval: 5s
            tlsSkipVerify: true
        withCredentials: false
        basicAuth: true
        type: prometheus
    name: prometheus-grafanadatasource.yaml
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-11-13T19:45:06Z'
    mac: ENC[AES256_GCM,data:I4wuLaEH+fbdSZ1evtbbF9IlpkP6mZReE8yoB2oPWiJP2AFJwjPVzDHeMSeGh1Ldu1aejHc3vwrBd/tKJ2cfrA1EGYbWSe/eV7WohRt/eXpWECz9YZLd2SfLU48/UpxnF++SlnB+3nr2scwWHiaIq7ZgWrXYzfDaPzYLMY4BZ6Y=,iv:u0EVd8zr6bfdSkSTQS9Bv6QYHEOBtq7UQCafDxbHFGU=,tag:DLIvvPJ8gfaj6L57+8368g==,type:str]
    pgp:
    -   created_at: '2020-10-26T18:51:40Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf8C5OrOjFqx+OereV9moIk4v3ZshMYvDkyKhkRgNyzUxN6
            lBiT3rlkcdvkifLX5LsHDu04buuOiYKSyCvmdeEP3kHzJ3chEdOVrnmKXl3QLvN2
            rAMyWND8dy7+R+ajwwwKByHSz5tgfqijQYKhaF/st3tJo7nMWR4KH7qGGKW6H8su
            VmHhHcEAd7AAOoD5A8f6BAGycq5ImWIHBKT8bEEfQNqE8B6EtF7HYZneYYscyj6V
            Ji4avJOLXEb2grHS9gjm0A3DY5KtIdMhj6PI/JZH2wUdGnnpNyRaAwcqcVVvJgtI
            oiCqWXNs8Nv/ri728seHdqdvWwjuBtRftKwyZnEyQNJeAS1mfsC7vZM8mFhRYvNh
            MwfnriskLuelkUIuqhuxoHcZUhxpyFaVRb4SzJ68tME6CvIo+chMm+Rq5cCJ+jjG
            k9DRBITwO94b5Cp7kW3qnIdv6NM7l+J9HWuIv6VUZg==
            =rtl4
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|basicAuthPassword|admin_password)$
    version: 3.6.0
