---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
files:
  - ./alertmanager/secrets/proxy_secret_alert_manager.enc.yaml
  - ./prometheus/secrets/proxy_secret_prometheus.enc.yaml
  - ./prometheus/secrets/htpasswd_secret_prometheus.enc.yaml
  - ./router-ca/router-ca.enc.yaml
