---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana.yaml
  - subscription.yaml
generators:
  - secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - files:
      - configs/ldap.toml
    name: ldap-config
