apiVersion: v1
kind: Secret
metadata:
    name: usir-stage-sync
stringData:
    rclone.conf: ENC[AES256_GCM,data:WVCGtAsO4FPHCSv10Zthw15trgJJACZ6GSIsRn6P/xuQuw2iCzqT4Gj5lfNW7qMfJ741e8Qm8JdviV2c5zSFlLLRtTq8Gq7qnDCogUox1EE5jv71R1iQiLzTyEg3+4A6TtM+WnJA2ABViLL0s6KCzkTfcpDkL0GlWh8EwEmyibnJL4HKJbgmfpkcm3D9Gl0qdp7AQFq+MWWbtGMuINseF4Q7PFPGYfBoJfA/ahe5Uis6WWv0mqAZg01cNQWbQRwJz+rzb7JSvAmNobA8hO9tLRvKtJkOn64nm3LuOK10aYnzx6v5kYU+Jmf+lTJH1AV4j3kz+loS0aDOuBaDZrUZjHB0/iLdj64XeICGKyXtGj3kYS91WpSALfikVjTNi+CHlajKT3M5QcSjb39xPC5aVwbJYmghX1JaM700myAZIRY15ZSovef8BsMBRDHblUFM5vnemOO8JJzhQf2xiwURtcXfd5R7EXJ6IFwXmhTZr02bro5MHF3d,iv:p+IulvFU9W8v1v9qx25NkiPsyGhuFtK4vRgsm08ztoQ=,tag:6/jm+0onjjVZVlZCrZfFAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-06-13T19:53:11Z'
    mac: ENC[AES256_GCM,data:UaKJwSkfOdtdQXOIbnm2SPFJL0XmoE66hYjswtpKhMklh9HC/gRrPZj6T+PvYdrwg/WBd3sqo3P1Gja9KBKmDzj9aokMisIfnvR27n7/ZWttm7gZtxboU+BCWooh0sILzy+MaJEczU+QswHYPtR3xBn1QmB04T2FccG1PzBMUro=,iv:iR07zfPFcT+kZObE1rHBLqtmhjXdGNKnmB9s+5DbSJs=,tag:JxG6cw4maeAoeCFhoNb4UQ==,type:str]
    pgp:
    -   created_at: '2022-05-10T19:57:29Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+PwQMw84w/rdAQwA6NM4uRVb5PXolceFxNxz6nWPxbnHD
            a87CdARVb/f8Jtqt/aE4Kf3jNFGTkFr7a06MZOGrQ5rT8ggZG9H0zdVPuVsu9yy+
            kvfpscWfSRl42gbiHCZLbztDZpRhFGa78sY1m94RUTVIMhjYP7h+pv/xMN8U9VmP
            0L2gUU2HdmmjOTFRvz2TN1savibeTfLxCuZu29p0dZOs3hb2owgDFu5Y80hSHqTe
            fA2rAr4OwK2vMRMhF0xB8AMjxQqeQM2If/An5SBFIOsK1GciHJRdd0BFAhF24/jg
            jol7s/NBvNa+obKKggRZRQbeqIUghECFV1NNg7g/qNJeAUrD0tJuUc/jNOippvH4
            8vpa5RE0YZbPrqIuhog/IEiBuTfYu1JJf3cH7mPoeKSW3vLwkb3Md0VlMMkGBqio
            jCqe2Whd83EeHpTKenH6kHfv+R4jehjsaGVH/i/CMw==
            =131w
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
