---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dh-prod-monitoring

resources:
  - ../../base
  - dashboards

generators:
  - secret-generator.yaml
generatorOptions:
  disableNameSuffixHash: true
