---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cpaas-sync
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: quay.io/rhn_support_sreber/curl
            args: ["curl", "-X", "POST", "--data", "{}", "el-cpaas-sync-listener:8080"]
          restartPolicy: Never

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cpaas-listener
spec:
  serviceAccountName: s3-sync
  triggers:
    - name: s3-sync
      bindings:
        - name: src_bucket
          value: DH-SECURE-CPAAS
        - name: dest_bucket
          value: dh-secure-cpaas
        - name: rclone_params
          value: '--s3-storage-class=GLACIER'
        - name: sync_config_secret_name
          value: datahub-s3-backup
      template:
        ref: s3-sync
