---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: marketplace2psi-sync
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger
            image: quay.io/rhn_support_sreber/curl
            args: ["curl", "-X", "POST", "--data", "{}", "el-marketplace2psi-listener:8080"]
          restartPolicy: Never

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: marketplace2psi-listener
spec:
  serviceAccountName: s3-sync
  triggers:
    - name: s3-sync
      bindings:
        - name: src_bucket
          value: open-marketplace-prod
        - name: dest_bucket
          value: DH-SECURE-MARKETPLACE-METERING/production_data
        - name: rclone_params
          value: ""
        - name: sync_config_secret_name
          value: marketplace2psi-sync
      template:
        ref: s3-sync
