---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: tower-analytics-stage-sync
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: quay.io/rhn_support_sreber/curl
            args: ["curl", "-X", "POST", "--data", "{}", "el-tower-analytics-stage-sync-listener:8080"]
          restartPolicy: Never

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tower-analytics-stage-sync-listener
spec:
  serviceAccountName: s3-sync
  triggers:
    - name: s3-sync
      bindings:
        - name: src_bucket
          value: tower-analytics-dbdumps-stage-s3
        - name: dest_bucket
          value: DH-DEV-TOWER-ANALYTICS
        - name: rclone_params
          value: ""
        - name: sync_config_secret_name
          value: tower-analytics-stage-sync
      template:
        ref: s3-sync
