apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: "trino-partition-metadata-update-workflow-"
  name: "trino-partition-metadata-update-cron-workflows"
spec:
  schedule: "15,45 * * * *"
  concurrencyPolicy: "Allow"
  workflowSpec:
    entrypoint: cron-trigger
    onExit: exit-handler
    arguments:
      parameters:
        - name: alerts_to
          value: 'data-hub-alerts@redhat.com'
        - name: alerts_from
          value: 'dh-trino-alerts@redhat.com'
        - name: alerts_smtp_server
          value: 'smtp.corp.redhat.com'
        - name: argo_ui_host
          value: 'https://argocd-server-aicoe-argocd.apps.ocp4.prod.psi.redhat.com/'
    templates:
      - name: cron-trigger
        steps:
          - - name: get-all-partitioned-tables
              templateRef:
                name: "trino-workflow-templates"
                template: extract-partitioned-table-names
          - - name: partition-updater
              arguments:
                parameters:
                  - name: table_defs
                    value: "{{item}}"
              templateRef:
                name: "trino-workflow-templates"
                template: update-partition-metadata
              withParam: "{{steps.get-all-partitioned-tables.outputs.parameters.tables_list}}"
      - name: exit-handler
        steps:
          - - name: notify
              templateRef:
                name: alert-template
                template: notify-template
              when: "{{workflow.status}} != Succeeded"
              arguments:
                parameters:
                - name: argo-ui-host
                  value: "{{workflow.parameters.argo_ui_host}}"
                - name: alert-email-smtp-server
                  value: "{{workflow.parameters.alerts_smtp_server}}"
                - name: alert-from-email
                  value: "{{workflow.parameters.alerts_from}}"
                - name: alert-to-email-list
                  value: "{{workflow.parameters.alerts_to}}"
