apiVersion: v1
kind: Secret
metadata:
    name: trino-config-env-settings
stringData:
    query_max_memory_per_node: ENC[AES256_GCM,data:G5qn,iv:xtS10j5uS6hUyvUVcKgij95N2N1/nVyvjnh8kdU18oo=,tag:WjyjziCoRlKyC8Z4iiiR3w==,type:str]
    query_max_memory: ENC[AES256_GCM,data:tTV+,iv:yu1ax2YJq3zC/TJfZ82w5QWAhfHEj9e3mgTTNgUyNjw=,tag:4T/oUtkNPYZCy0yEbOxXcg==,type:str]
    internal_communication_shared_secret: ENC[AES256_GCM,data:b8BF6D3BS6Vc5xg/p7vKlKoZud0cWN40ZmBavG3s7kf3D3SV8UgLuDFb4MwTpCmXkTvYcwMdEQFvntdA5dM6f6OdWoRkUC7AwU6NIYHB+dGy1DCa9Mdu1iG+cBG5pTIXcUK4zCCmzc5GhBp4sLD+eE/azJ+S3zn0EE7IbF487JIg4f6FW7KKgWvwiP+w6MWY6RiqhT6cPdG7QiYyfNmkTv5PgPRcY3NMqOEC8lFNqhySVjYF+OA2/oTsckNbxYPx0b/gnXLV/Yy4ApvwqI4YdWaDyn8OziqlNg3M5H1rq5upXu+mF0wuy9rLnxfiCoJTFY/Sofj6MhhH7/DDkb+Bw98zqcZaVU09OsUUdlO+sQ4naQeuVq/XaAwwEfIbelsjM8Fwm7URHOKhhQzZYb4vso1/SDxkQz58vjsngd0ApwOJJRaHfKJwSO+PODeJ99vLRHr1LPAypEUKdgZOZvUpTSEN6qL0de/sZ0DVIrTLyIRUuzii3xJkjg0FBReG8xwQzu+H1h9rWLLsAQRnWLOFxZAZ5/qlYRGOjDyWeneEel3CmxnVrOT2HqR28Glo+WqVIllJYCF4FhX5fIxBhjmqmtXRFjevODdprtyW+0utp3dPVpkuLYnJybCLwty168ecYMCOGw7hAzhgzQi8wygL9SImzadbVZHSivLbWHyAdhbdfboF6ZEWZ/DfWu5XFdHN9eWEd+rqRVzaQ32Mf/qmhf/i2J9PO3ogetsBkyE+ntuaMcknWFxdl7BSux56kI5+IKcsI4KGjG1Tg4NdAZ492SJDWnl3AFv93j2IssoYprP1OkCn2SnZPqrH/WVhlBB429irfdHozqFyioiRVNmb/gV/9FdYgnTOudIeF2R6QZrUzsXDPdlZDk4v0aLh83VimODfnp+7LDQXCabD,iv:I/Bbt0kSA6jx4RuojuQVwzxNLCLr4IowQ97IaE4C9mY=,tag:Ffy5l6USYIMSi5JD9GFNFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-08-19T19:28:57Z'
    mac: ENC[AES256_GCM,data:3mdyJoJt9oBEJ0NxCfaO51VJfxBcFP9CNaI3zRgui5BVVF8yh9wtJQAHEGwOuq7khHgbprtaD36EeujbCuRaDr9Ljbx0uPSEAXEyo5+n92tV3uxg7JBbuNFlI7dp1t8nTxWVk/Ti4hrzFdyH24wo9XlNeqDUrAh25BrO+PlpWxs=,iv:JOCnjTOJexDQQcSHklC9oAeqUUUFnmdyFaqwsI3ShGY=,tag:Kf5uGdne9yc3kRN5Zkntjg==,type:str]
    pgp:
    -   created_at: '2022-08-19T19:17:23Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf8CCoWVJVz7ZYtGnbeWs0amiTEILcJKtjr6I/OecONa28K
            Byc14n+q2TcnnHsQSyS/WoFdgQ/sCObWyyZRLQotds/eHHOpIyBgXX8s8lHFYQUP
            IDsTpCOrDTwizL5UBnP2NQV6qNpethjK314rbAIcNqmt/0SzAwzpiUmb4jApQNrX
            bGjLGM15ba8FAKGb3/RS6G2+uasYUyzweLk0ZehD+INyjGTCuWHB9inZzDhBoFNw
            DgL1fM7+ZhxHu2tBsHAnQhaVdbfmeaKgNn6unxFXYPHjpcUXot1EBKGov7MhDz7S
            gArScK3W5fRJvfNJrCTq/r7z7sUrQpjA4V1zCy7pLdJeAcSPYB0qvm1m7uSsgSAJ
            xLNtN2VFF1s3P6FpDM4vOVC3etVo8S9i/eY/gvIP5NW8MDRszOVGzJFpkGVRr+88
            mkY1vLHqfbk+ru38aM0pD2tqbb6dzBwAi0JnJdtdDA==
            =vKxW
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
