---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: rsyslog-ingest
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: rsyslog
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER
              value: "kafka.datahub.redhat.com:443"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
          volumeMounts:
            - mountPath: /etc/rsyslog.d
              name: rsyslog-d
              readOnly: true
            - mountPath: /etc/kafka/certs/
              name: kafka-cert
              readOnly: true
