apiVersion: v1
kind: Secret
metadata:
    name: marketplace2ibm-sync
stringData:
    rclone.conf: ENC[AES256_GCM,data:ujE1e1EYeNwj7WoaFw39K5S7ip1bGoxQqyk0EgQCDckhOyWq5HpMhq7DeVTlZSXvFS404fJf+Ojyf2l4FpWyHHs3bcZAW9CldPmQWV9FkoCn2dPV+6GnkC5UtVc+f98sipoAlkIRu1z3wIdLSJmviBdLm5eIxA9pEG3KOnRisqUPgB2ym/bKbeKUdaCXTim3ltIrQMupC3vJN6oRbEOrMjlsZub2tm7LSNuqmWyc7QNVvoaXH4DguaBjl9VApGhL+zI/giPOd+C7JmyQaWIIG6qnrGZbPzQVgH2Gp9Om492EBWFPq4F8j2ylF6ebXLuoNo8S1CUkc/XmOcHl0SsVQLtxr8/u3QwPn9N0Mn/m8yBp+Fca93y5Zj1lCXQ/aDVKSk/reJA0H1Yhra8hQoAmF2eL2hL+WtEFNa9WHFaZDd1b8SpcOhHIPlNeN230l1R1QspJoUBOSDPlEiBktRmCu7ElLZFeon7lPB2qKJYg8+s2fJf5/eClNYtfDiC0APZqqY2AtP+aPXkdZBbObtaB6XYz2sw65jbUFomvBIKbzejeQ3VMAu4=,iv:iiSvG+MMCnPwYzeqYs4MF2kAp294x30O7aM4gfzu7/g=,tag:7b2yTS6fseUuNaG2HfxR6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-05-06T20:04:50Z'
    mac: ENC[AES256_GCM,data:QbvsbDYxwypTDa0oTz4SkukocmpJBBSSwPTitKMjns7t3Libcduz6AvZNjyXDLhjMAyUii6CZ65f73L1MnmYT/xdpRP5MiCVzArxGxRGUDf3sE8Bl+yxzWRzkBZmFVezRgcDCDTpKNBFd/jWArcPwp8KEDkRQn20HFE2Hi7aJ/o=,iv:AwxKccXAHkRd8Gc35phopDme+//lVszXkFPFnKAGCuE=,tag:tr8ejr09BDrPluaC83jxLA==,type:str]
    pgp:
    -   created_at: '2022-05-06T20:04:50Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQELA/irrHa183bxAQf3Wt1BqEbTscw4Vqz70LqwrZe/tBTDME2OFmdgcrUL/11b
            jnrmGtXb+Cesc2JaemvDGZasvBYNTqOv/IZnbNPOYHgDCQvTl+2I4ELtDf9WUcd3
            kiQ9u+pxTQoQXBOpBY1DiE9GY3GK8+10OtfrxLDUGS8tycs9wd1wgkSajZ6exNhz
            Ayh+rBEvuk8ZH07VkyhI9XLtq7ELFqAB1+ZjHqSVhNaBY+VGOq1EstVbz6LneeqK
            /NZnStK3uPWFd0mApRXKHcHjJA2nKuawr5q3pOSp7mIXdLrhrapRKs9GUHjeVNZp
            RCnKtZTyJf7QL8s1cQE1IAR13Mi+rckK+MuxrHox0l4BjVGM6PyMjdLPp2kU4n2g
            w61oEuLhDhB9UY0AIoUTEWIlK2pDc7xlVXJt20mAixVMOQiZRMSi1AnTMwzjIpzl
            uHzuEv1QdXffvTWLSvHshFdgk6ZwSG0tQsNuY8a3
            =gIhm
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
