apiVersion: v1
kind: Secret
metadata:
    name: tower-analytics-sync
stringData:
    rclone.conf: ENC[AES256_GCM,data:2bJZGxNW7yKTomA61yOQ6254vjnjJnYIi4NSekbofU7azePm2KkUvTMTomIAbyjxCNMliUM2V9AQaOaa1LGUL4fDKEoLGDVru+9kZ8uvxeRhZ66YgODvmvSc0lgLsAn82mIDX66DDan72fQruYCnBXdFv9Ro5PfZNwae6n7cxB5gxsWcB73Yr0g4z6wGOXo1wcH/Npt9Eat8/i+YH+uwhpxeOd/y2xgHSkrIFN160gqR0OdamoXJAChMP+oqInjq6v/V/aFjXhH8jHwXRlLtwnXtdEvhvm1g6pHmTMW2FIhLCrel2sQKWxeUTR1fMNnV9xbGAOBv2U34sEhOWLvjs2w5K/R9MUAfdYtC5PbCFD7zNrb8F/Pgpp3hFWpil9mGucmBsYkOL6N7iZXAfdpROM7pm/IKgHQHbWjmEOsCOnmncyrywLUWnO/fUQp61zlzQ5bl5xHkJyJMCBpIwncX+ubNFjZUWGEN0RyBjCeLTAG4sx5zmcDC,iv:j7GpLPOi7qQXimulHpulx2o04E+Q923SwffIz1d6cCY=,tag:6v4fvRZ9sKm7qh0yRon2Yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-05-06T14:00:26Z'
    mac: ENC[AES256_GCM,data:tOjD0W+E+utT9T+qpzbHo1MI0zwgDmqQR016rGridShPMtlizb3fX0t2trL+QnnsVPvhSYgnwsbn922lFnI4sY0E26cw6iHbnyiKn9ZQEDgf+EeTBG9EOmbT6mE8Ava0FST/IbOVWwKdI/jZGTCGTvHhgJ7ISwjagdQwCZfU+p0=,iv:Wy2bI+OLvsZmHIh6SH34XUUTeb48ByQhOHAX6vtlY+k=,tag:ushie3696Kt1dcl3RKBeGA==,type:str]
    pgp:
    -   created_at: '2022-05-05T14:13:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+OEsmpTnmTxLA3gDZ7WRWaSCioNJHIagdccHvuyFMTkqU
            K3jBQrG08+aSwdechHOKO0h6/UwpKHeUR1a8v/m9PMepJfhxJy92jXC+R/uywq1L
            TQ24n2Fx56cGuxWIRLvCzMcTXvMzjM4vd7BJa6LCI4ezJCNv8kEkrn+YHtQCT+2h
            InBQ5o2HHeK+pFqQH1EugbWEumfpSGK7eJ7inHC9adfNs6l0REwStb1XKW26VZ3j
            3ejcq4G912XBAI4gTjURMIbjjK93ugAKZGU5ya+MzmxpN2aN0nHv1uEC0fAjfxVP
            0hk+1BUzuIwBmXoikDiEFmncXQYHrqH3FilXp7Dxy9JcAThmeBEVRMkODt4RAeMu
            I0yl0+FjBO9lbDPGz1Nm912n8RCECIq8xI5NhzvwZod0ogsPbHYam5Nyr+R++S1F
            0iQeBzZ1IwYyQY7pM0vmchC9iGqZS/+5wCzs1ZU=
            =f/fp
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
