kind: Secret
apiVersion: v1
metadata:
    name: redhat-rhods-pagerduty
    namespace: redhat-ods-monitoring
data:
    PAGERDUTY_KEY: ENC[AES256_GCM,data:2f4nIjzllw==,iv:rui8Ej7ZzEZC8VwzjmNUXzp4S4Ra8NC39SDJi+jGtTI=,tag:azpj1JGOZTHWItBd4/IPnA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-09-29T17:58:02Z'
    mac: ENC[AES256_GCM,data:cdPCA6SHmTLn3t7DLUrPsg0ANO1Pw0pSCbBFpGrbzgAqUHvvsF8dw8YDEbI5qDUd9AREdqC7DDj3GQhrMyv3I3Lh3YafEFfHBGw3wThF+r8OkTiX4nnOviHj9ymLnKmy9+fSMquoILLoy+3IwsQlTgHdikJCT7kDb3VMuq3q9sw=,iv:/W7SdzhdmtEYpY/XQsWIBDgl65z7e03jnMSm8i/ViaI=,tag:LbBAjeZYkBNiuxXfEdjcUQ==,type:str]
    pgp:
    -   created_at: '2021-09-29T17:58:02Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+KQHvTwB0vuSUFncZub+3RRzgkxhU3IlzMSGG9AsasEm/
            c/OuGLLHHZ/pwRdjhorG9O2+723iGca5wB3tyVPAX8gJAd9IO3fo52sncuGYgZ72
            sMMUefMWD4Kky/eR4pQvBo8WqjAgDeYsEUjNz2ry80CZcviQxAT/pFBRIpU0Ijd7
            Zu881Em22XEVYd0Wl2tspEpj3vBORUoIjOuyZmoUbjOdbsaR/GvJRhab6J51ph8K
            3sAk+E2yM4Q+7SJHcg7KxM+He7tNKuwjmnPO1Q/RBPuWIDoM6c3LVYiboWQMAGUK
            nK3JKRJZVIvNZEsWZscuHZ7n5Sg7Lh6Xj4jvyenw8dJeASbzrq9thTMRPpsQ6Kru
            KW4fGIZZy8cRFQ4w8SxO+FBvQ+o3H4a6htOsQGprDtrmP1Qv2+9I4nD1tN5A9f84
            lQB63j4EvTBOqPWkRRiAtddjr7gdIguqMYNlH9YaPQ==
            =rD6N
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
