---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: idh-kfp-tekton

bases:
  - github.com/operate-first/apps/kfp-tekton/base?ref=45c62b24d4b02274e375e83556c7654c0d9d5dbd

patchesStrategicMerge:
  - kfp-tekton-config.yaml

generators:
  - secret-generator.yaml

generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:
  - patch: |
      - op: replace
        path: /data/artifact_secret_name
        value: prod-mlpipeline-ceph-artifact
    target:
      kind: ConfigMap
      name: kfp-tekton-params-config
      version: v1

images:
  - name: docker.io/aipipeline/metadata-writer
    newName: quay.io/internaldatahub/metadata-writer
    newTag: 1.1.0
  - name: docker.io/aipipeline/persistenceagent
    newName: quay.io/internaldatahub/persistenceagent
    newTag: 1.1.0
  - name: docker.io/aipipeline/scheduledworkflow
    newName: quay.io/internaldatahub/scheduledworkflow
    newTag: 1.1.0
  - name: docker.io/aipipeline/frontend
    newName: quay.io/internaldatahub/frontend
    newTag: 1.1.0
  - name: docker.io/aipipeline/api-server
    newName: quay.io/internaldatahub/api-server
    newTag: 1.1.0
