apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: obslytics-data-exporter-workflow-
  labels:
    owner: obslytics-remote-reader
    app: obslytics-data-exporter
    pipeline: obslytics-data-exporter
  name: obslytics-data-exporter-cron-workflow
spec:
  schedule: 0,30 * * * *
  concurrencyPolicy: "Allow"
  workflowSpec:
    arguments:
      parameters:
        - name: start_timestamp
          value: "{{workflow.creationTimestamp}}"
    ttlSecondsAfterFinished: 86400
    entrypoint: cron-trigger
    templates:
    - name: cron-trigger
      steps:
        - - name: trigger
            templateRef:
              name: "obslytics-data-exporter-workflow-triggers"
              template: trigger-workflow
    volumes:
    - name: obslytics-data-exporter-workflow-secrets
      secret:
        secretName: obslytics-data-exporter-workflow-secrets
