apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: obslytics-data-exporter-workflow-triggers
  labels:
    owner: obslytics-remote-reader
    app: obslytics-data-exporter
    pipeline: obslytics-data-exporter
spec:
  podGC:
    strategy: OnWorkflowSuccess
  templates:
    - name: trigger-workflow
      steps:
        - - name: run
            arguments:
              parameters:
                # This is always overlayed with a full list of metrics
                - name: metrics_list
                  value: '["cluster_version"]'
                - name: start_timestamp
                  value: "{{workflow.parameters.start_timestamp}}"
                - name: step
                  value: '1800'
                - name: delay
                  value: '36000'
                - name: resolution
                  value: 5m
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: init
        - - name: get-all-partitioned-tables
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: extract-partitioned-table-names
        - - name: partition-updater
            arguments:
              parameters:
                - name: table_defs
                  value: "{{item}}"
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: update-partition-metadata
            withParam: "{{steps.get-all-partitioned-tables.outputs.parameters.tables_list}}"

    - name: trigger-backfill-workflow
      parallelism: 3
      steps:
        - - name: normalize-timestamps
            arguments:
              parameters:
                - name: backfill_from_timestamp
                  value: "{{workflow.parameters.start_timestamp}}"
                - name: backfill_min_ts
                  value: 2019-05-30T00:00:00Z
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: normalize-timestamps
        - - name: run-backfill-workflow
            arguments:
              parameters:
                - name: backfill_count
                  value: '2'
                - name: backfill_from_timestamp
                  value: "{{steps.normalize-timestamps.outputs.parameters.backfill_from_timestamp}}"
                - name: step
                  value: '1800'
                - name: metric
                  value: "{{item}}"
                - name: delay
                  value: '43200'
                - name: resolution
                  value: 5m
                - name: backfill_min_ts
                  value: "{{steps.normalize-timestamps.outputs.parameters.backfill_min_ts}}"
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: backfill-metric
            withItems: # This is always overlayed with a full list of metrics
              - cluster_version
        - - name: get-all-partitioned-tables
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: extract-partitioned-table-names
        - - name: partition-updater
            arguments:
              parameters:
                - name: table_defs
                  value: "{{item}}"
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: update-partition-metadata
            withParam: "{{steps.get-all-partitioned-tables.outputs.parameters.tables_list}}"

    - name: trigger-verification-workflow
      parallelism: 3
      steps:
        - - name: run-verification-workflow
            arguments:
              parameters:
                - name: verify_count
                  value: '12'
                - name: verification_from_timestamp
                  value: "{{workflow.parameters.start_timestamp}}"
                - name: step
                  value: '1800'
                - name: metric
                  value: "{{item}}"
                - name: delay
                  value: '45000'
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: verify
            withItems:  # This is always overlayed with a full list of metrics
              - cluster_version
