apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: obslytics-data-exporter-workflow-triggers
  labels:
    owner: obslytics-remote-reader
    app: obslytics-data-exporter
    pipeline: obslytics-data-exporter
spec:
  podGC:
    strategy: OnWorkflowSuccess
  templates:
    - name: trigger-backfill-workflow
      steps:
        - - name: normalize-timestamps
            arguments:
              parameters:
                - name: backfill_from_timestamp
                  value: "{{workflow.parameters.start_timestamp}}"
                - name: backfill_min_ts
                  value: 2019-05-30T23:59:59Z  # TODO: figure out a way to determine this dynamically
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: normalize-timestamps
        - - name: large-metrics
            template: large-metrics-backfill
            arguments:
              parameters:
                - name: backfill_from_timestamp
                  value: "{{steps.normalize-timestamps.outputs.parameters.backfill_from_timestamp}}"
            continueOn:
              failed: true
        - - name: small-metrics
            template: small-metrics-backfill
            arguments:
              parameters:
                - name: backfill_from_timestamp
                  value: "{{steps.normalize-timestamps.outputs.parameters.backfill_from_timestamp}}"
            continueOn:
              failed: true
        - - name: xl-metrics
            template: xl-metrics-backfill
            arguments:
              parameters:
                - name: backfill_from_timestamp
                  value: "{{steps.normalize-timestamps.outputs.parameters.backfill_from_timestamp}}"
            continueOn:
              failed: true
        - - name: get-all-partitioned-tables
            continueOn:
              failed: true
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: extract-partitioned-table-names
        - - name: partition-updater
            arguments:
              parameters:
                - name: table_defs
                  value: "{{item}}"
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: update-partition-metadata
            withParam: "{{steps.get-all-partitioned-tables.outputs.parameters.tables_list}}"

    - name: small-metrics-backfill
      parallelism: 18
      inputs:
        parameters:
          - name: backfill_from_timestamp
      steps:
        - - name: run-backfill-workflow-smallmetrics
            arguments:
              parameters:
                - name: backfill_count
                  value: '2'
                - name: backfill_from_timestamp
                  value: "{{inputs.parameters.backfill_from_timestamp}}"
                - name: step
                  value: '1800'
                - name: metric
                  value: "{{item.name}}"
                - name: delay
                  value: '43200'
                - name: resolution
                  value: 5m
                - name: backfill_min_ts
                  value: "{{item.backfill_to}}"
                - name: worker_size
                  value: "small"
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: backfill-small-metric
            withItems: [] # This is always overlayed with a full list of metrics

    - name: large-metrics-backfill
      parallelism: 3
      inputs:
        parameters:
          - name: backfill_from_timestamp
      steps:
        - - name: run-backfill-workflow-largemetrics
            arguments:
              parameters:
                - name: backfill_count
                  value: '2'
                - name: backfill_from_timestamp
                  value: "{{inputs.parameters.backfill_from_timestamp}}"
                - name: step
                  value: '1800'
                - name: metric
                  value: "{{item.name}}"
                - name: delay
                  value: '43200'
                - name: resolution
                  value: 5m
                - name: backfill_min_ts
                  value: "{{item.backfill_to}}"
                - name: worker_size
                  value: "large"
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: backfill-metric
            withItems: # This is always overlayed with a full list of metrics
              - backfill_to: 2019-06-01T00:00:00Z
                name: cluster_version

    - name: xl-metrics-backfill
      parallelism: 1
      inputs:
        parameters:
          - name: backfill_from_timestamp
      steps:
        - - name: run-backfill-workflow-xlmetrics
            arguments:
              parameters:
                - name: backfill_count
                  value: '2'
                - name: backfill_from_timestamp
                  value: "{{inputs.parameters.backfill_from_timestamp}}"
                - name: step
                  value: '1800'
                - name: metric
                  value: "{{item.name}}"
                - name: delay
                  value: '43200'
                - name: resolution
                  value: 5m
                - name: backfill_min_ts
                  value: "{{item.backfill_to}}"
                - name: worker_size
                  value: "xl"
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: backfill-metric
            withItems: [] # This is always overlayed with a full list of metrics


    - name: trigger-verification-workflow
      parallelism: 3
      steps:
        - - name: run-verification-workflow
            arguments:
              parameters:
                - name: verify_count
                  value: '12'
                - name: verification_from_timestamp
                  value: "{{workflow.parameters.start_timestamp}}"
                - name: step
                  value: '1800'
                - name: metric
                  value: "{{item}}"
                - name: delay
                  value: '45000'
            templateRef:
              name: obslytics-data-exporter-workflow-template
              template: verify
            withItems:  # This is always overlayed with a full list of metrics
              - cluster_version
