---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internal-data-hub--superset-stage

resources:
  - ../../base/

generators:
  - secret-generator.yaml

patchesJson6902:
  - patch: |
      - op: replace
        path: /data/superset_secret
        value: stage-superset
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_db_secret
        value: stage-supersetdb-secret
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_cpu_requests
        value: "1"
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_memory_requests
        value: 1Gi
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_cpu_limits
        value: "2"
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_memory_limits
        value: 2Gi
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_db_cpu_requests
        value: 1000m
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_db_memory_requests
        value: 1Gi
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_db_cpu_limits
        value: 2000m
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: replace
        path: /data/superset_db_memory_limits
        value: 2Gi
    target:
      kind: ConfigMap
      name: superset-config
      version: v1
  - patch: |
      - op: add
        path: "/metadata/annotations"
        value:
          haproxy.router.openshift.io/timeout: 200s
      - op: add
        path: "/spec/host"
        value: "superset-internal-data-hub--superset-stage.apps.int.gpc.ocp-hub.prod.psi.redhat.com"
    target:
      kind: Route
      name: superset
      version: v1
  - patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 10Gi
      - op: replace
        path: /spec/resources/limits/storage
        value: 10Gi
    target:
      kind: PersistentVolumeClaim
      name: supersetdb-data
      version: v1
