apiVersion: v1
kind: Secret
metadata:
    labels:
        app: supersetdb
    annotations:
        template.openshift.io/expose-database_name: '{.data[''database-name'']}'
        template.openshift.io/expose-password: '{.data[''database-password'']}'
        template.openshift.io/expose-username: '{.data[''database-user'']}'
    name: stage-supersetdb-secret
stringData:
    database-name: ENC[AES256_GCM,data:kaAUzbUucB8=,iv:E7IXDgJax587Ckrq/uE1zzLAHq926jjl2kxY5YLwVm4=,tag:YDGnnwUaigUd0xtLeAIczw==,type:str]
    database-password: ENC[AES256_GCM,data:CVW5dEZMGGc=,iv:S9lE69CFiwJJMezmZLibw5Lq+B5bTd2IuNl1ztY9PW0=,tag:YfxXWel27nt19y9go/wamw==,type:str]
    database-user: ENC[AES256_GCM,data:jfKGOFN5KGs=,iv:blkrzamwNlDFjgMokMO7zV67P/EwhvE5AuQIuuhRrK4=,tag:2FGNHCjjvrmT0ZPi1xQ0dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-07-13T21:11:23Z'
    mac: ENC[AES256_GCM,data:K7NO1RsxPURXUyl0OWufz7aubDuGAcNAZd3VHUVn0MRdy4S5aENQqWkAr9PXiuRrF7c+tCl/7xrw1PC72OUsip7Khnh6lwpwsmwF8y0Y12AXMVAP3T5Z8OYyM/+b5qr7ZbC41QsJri6XOxs6GpKZi7eyEyJInlFzH08FpAD/Y2M=,iv:HW7OzDsENnWj4lKSVU1DC/QQ8yAEAntgdQonbc7M8vU=,tag:c2bdZlyZOyqFPs7A8122Qg==,type:str]
    pgp:
    -   created_at: '2021-07-13T21:08:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgAkN2wzuGPO1ToAIsAXw5Wh7fHIQvXr6KcZ1DQSqA5+71c
            UclEFHQP0lAELpdOJhFUxUtlojyo2xr2/00G46b+wsxnIxroKsZgThtosYLgf6He
            9gfKXCtsjYsvJavnpjOdxLOlWZPVZ9eAXVZZwJClrsbYn4zG1cBIc1sK8VGqfSXu
            Xu+bMlKbaEkxlEQWeZXx9O4AP9suaLS9+pAHUtANHAT9lRK8FNf2F93q0CtR5vcU
            kd0dBrQE+IBdjifqOHFy7/My/Bz3slGIXnfDdSfq4hr1pQhazwq9uuZuvT+O6wJI
            7jYNM7MEiK8D7Y3rgBlFJkEsJropQqVRXfYjBzyYf9JeARZ3mVTUKsoij671eaRK
            2BrQOwXWmZmqWn4A2tILxJXuyIl3FAtXN0LGUgmUz/WgBOU+Bku1F8fISvRNUj5h
            rq6kswOiT1YMo66aQFiU9o96FWqX2wYUMtFqX0CMOQ==
            =sFUD
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
