kind: Secret
apiVersion: v1
metadata:
    name: redhat-rhods-pagerduty
    namespace: redhat-ods-monitoring
    labels:
        hive.openshift.io/managed: "true"
data:
    #ENC[AES256_GCM,data:CBewggKJd8ZctkGJ6UNjt4vs6b8AtiZD4QuoWoYQzObM/Q==,iv:vXltWyR8bEhSe3+Gx67m7b6zmqPzylXp5UXlSdLViqw=,tag:rHgYeN2YYmUgiG48wxK3bQ==,type:comment]
    PAGERDUTY_KEY: ENC[AES256_GCM,data:bSuZOob7mMjE8Exu,iv:s+VsYl/f15WtGUWdbrG1RKYcm3uEtf59S70yOFGSrag=,tag:r2RPMsOOBBba9l20xe+smA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-21T15:41:02Z"
    mac: ENC[AES256_GCM,data:gsT7WqFl9eBZ5VX6SjoQN8Jq9/pKhr3aXC9F+zp6Iw5k0HW3LPozoMMWKA+2N+S81UUPAPK5Fx65yqX/I7zeO/IgDyQ6CmLK7v9pdvcIahhwC1a8G2n7pY/y3hAoz4qmx24c3ALkNXY6lKUw0N9hFsWpWtH23o/eUla+kYTzF9o=,iv:5bd6JWkuxsVCmvh+q5lLGi9UdpJP0vsft2VxLBwrerc=,tag:TRJlY/iUn1rsUX1d7bXniA==,type:str]
    pgp:
        - created_at: "2021-06-21T15:41:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQgAgXa9BX1QzPTSoS+cwlG8BZ3wLQVioOAJJUTjmGzS4eFw
            mRJBi1tosViAIy9Sq4UIrpyAPKEX7QhMuQZNJ5kNSUiqknkX6RwLXh0aYjS6w4rd
            F9ITXxzIt8/HFGxce36NBvSy9NZ75WS72DWx821IZw8X/2g13mT0+K5i3WnC0Y3K
            sT9YxTg0p2xXV8mQ90mGm5ZZ+/hC28jnQ39knQEDt1ahOcookA2l01RO53Se5B0r
            cnBRQXHNeTuWrhZP7BtwvPz/KdvQcVx9ZuaUnlfZ3ZDQsN9rqB9GIxWo/h3WfB/t
            qwc0XZZvisQCVFqhpgIWx+Pgicq+F6uNydKtnaytCtJeAWm7V48g09wehcgJ7ALG
            bjM0pVGt75Ct11biHIYNVXiPMzRzj7fiCrlWioRGX2+Bvpct1goyUxxCROVfn/8W
            ax950UpWu+gPfXHa4ovKgQ3yCmmUaoOmXOClfm4ScA==
            =EXy6
            -----END PGP MESSAGE-----
          fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data)$
    version: 3.7.1
