---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: idh-trino

bases:
  - github.com/opendatahub-io/odh-manifests/trino/base?ref=fa39cec574c523ae37b67f8a67b0e8bc476ce2a8

patchesStrategicMerge:
  - hive-config.yaml
  - trino-config-secret.yaml
  - trino-coordinator-dc.yaml

generators:
- ./secret-generator.yaml
