---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: idh-trino

bases:
  - github.com/opendatahub-io/odh-manifests/trino/base?ref=3f8aad85faa83bb73a07f294ed9e296da3ee2cc4

patchesStrategicMerge:
  - hive-config.yaml
  - trino-config-secret.yaml
  - trino-coordinator-dc.yaml
  - trino-service.yaml
  - trino-worker-dc.yaml

resources:
  - trino-service-monitor.yaml

generators:
- ./secret-generator.yaml

images:
  - name: quay.io/opendatahub/trino:361
    newName: quay.io/opendatahub/trino
    newTag: '371'

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: trino-acls
    files:
      - trino-group-mapping.properties
      - trino-acl-rules.json
      - trino-service-accounts-passwords.db
