apiVersion: v1
kind: Secret
metadata:
    name: trino-catalog
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    hive.properties: ENC[AES256_GCM,data:aHcd7J6ZKaB2tFWYqTlFSudtD6Fajxd4x94KenyCV/5hzqxATam71lrV4Qxtr+AkjlSfWZevATADnQ+g1PdakjOJ0pLnTNLe8hvhL63zylAno6Bn/LqTT5Rbf294eEZPVQKYkbTy7cvIVNWCHnGO3N5A8r/HKcVWyK9EyKLpB+jtJnl1Tg739wLD4Gdii/isSeMTfodvKzEwCxSzv/qKqAWg6e9O1451HBiUCyFUWkSW2EI5KT69MOi0W7gXZNhjGjJHfN60NFx7nud+jsWbqzpTpjBgb23mos4UB1awZWTVqF0tM1d8MWA4l9QLNKYzc+q0F2HoKb92w4C7HFXRgjatO3mkXrO3hU0vTCX7EP0TRPsEg//5XH7g4lJL49g9aGwTK4CDLuhJGlfZ3+xgSEjVA4dHO1DvV3HntvxIEYficpJ3AsOHJEKZW/y+KhHdzGiJ5RF3ZLBzw0abzVKzztvaF9+J6/V2VlsiFyhLVKu7Mz066SrR5gya1qJC0Ss=,iv:7Gqkahtjpv0GA/BhCpOSCTuaDKStszvBOlqgqhOhLjs=,tag:DhB24T5beGrprNALXDa9yQ==,type:str]
    jmx.properties: ENC[AES256_GCM,data:Sq4+ZfJA64R8OrVYqDzhOYeX,iv:DYyyarVT9jomzzD0onkInIlcg3uDJzNmpL+Q0h+eg+0=,tag:tici5mbwMamPOBty9lRcvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-08T14:26:01Z"
    mac: ENC[AES256_GCM,data:V7OK9Gu/GxqA8qELCtmtzAbPGmXLZpT2sKAM45lorUKOzZWueJUY0M74yG1D98vfqK7hMFqj4d9gJbcrudLj+Y9smCNTtpnBda+mK8QHqJPTPaUN4bn/8AVgr536hj0H4nett3YpJjL2azJfCublPPNtSZR4qoIfCCN1+LYsoPs=,iv:RGBquwpsjTDQ7FG4LxItsakxRiZVicyxdmRonitGxSc=,tag:ycYydVgBI2ilFMgLwQI9xg==,type:str]
    pgp:
        - created_at: "2021-11-23T16:15:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf9G7BAXL7L+FvDCsGD5rRgY2Zv+nPeIW2Hm+M+gUO4lyK6
            6RgYkvjE4x7I6mySwYjG2uX023RGavgIDPgeTGXke1tARRGUGysmzp59WLIdUrby
            fNnV3lKUwGoD/7X1AsIb+DDvOvuO2j0Anv9fNzIGEd8coV7YGjvl+m+X5AyIgnxu
            OWiJSbUxZbljnV9WrxpaVpCo6PtulmQXUD+9WRCj7ii4HUxv6NRwVi4yawXuR7pI
            5Mpz3OK/48SArBxxjgXlAf+wr8ZIptWJIMvxRr8pZMnNY7lffCJbmMpC7xtdO83x
            hT4z/AF4PWgYsxsM8cchBMbdjBkxiKeh+pf2L9c0XtJeAV1yIXqkT4wlYgPHPZCk
            bEZseXHbJzLp74WlempkVHWISJ3eHcSSshSpepj3+KT2IA1tQJdak5mTmR4GkT7S
            uu2carIeobyDglUhgF+nnJDsxwVJrRVBHeAQ04J6rQ==
            =Qw6n
            -----END PGP MESSAGE-----
          fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.7.1
