apiVersion: v1
kind: Secret
metadata:
    name: trino-catalog
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    hive.properties: ENC[AES256_GCM,data:9qWYAmBmsPQnJ4CJtKZmlaxOGkHGauW9hbAabfQndlZT8eQrMnM/wMtmBevNvIVXpT6M6ylQspybl6/47mBlRBiO+WHG0vhXz/1DTCRGP7+HA1yb5iZkZd0Ayl3OqaLFNtiY3GA3hwORNSrQot+HEY5JwoS+xnBXC443aSHPs7tkPHW1Lbcd65diz5JoPAuJbMyxN3iu09KhM1GE5BfjVI1xUubFiDObCEbgJvPs9l2bha1Cx/mxyWFATA8a6VVo2b3HY3vMTmd8T/gUt+G5WvgGB1pKGcR/5XQ/2ndDX9YIe5H4dmTiPrfoypur5kk7/ptBrdMmHn+bsvJd04cUhBTQwRYoP/tQG/UcoPBDiCCj6gAfVmvqbtzEbh9DOW4MnbPOc8iEWG5+nfm4WMoW4Kh7wKKeRrAFp5O0hvkCMusIwZeN5md95Ek5F4jPT99DOYIO8NtpvkZ+142FvuwyRdRQOmU=,iv:sN7rxDjxvKdMtg5iiNqfwasYcNEh6/HHaQ2xOuLsUqk=,tag:wtwcMjePL3tUXt7t6s5bSw==,type:str]
    jmx.properties: ENC[AES256_GCM,data:Sq4+ZfJA64R8OrVYqDzhOYeX,iv:DYyyarVT9jomzzD0onkInIlcg3uDJzNmpL+Q0h+eg+0=,tag:tici5mbwMamPOBty9lRcvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-21T13:37:41Z"
    mac: ENC[AES256_GCM,data:VlzlrWWUjPkpw+XxiPCvhGgWKOnM7Kttz3/CmCnN8Rtg/rZ9EOmZG+ylxnhSdZtfKNcwsDO5E1u1A7I3NZnqtBFthm1HNcnrSsGrjblSNDrYgEaFvoM3QT6mErvQ5WMWvfmjSKcj/E+0GdR8ypfHvFtB9QmweMzTrVkYJnIz+SI=,iv:D4gHO4r4xetSQWEm8Feo7Cy94LGEyaqSh7OuD7CH7mw=,tag:PmzaKJnHqmMP4J96ZCWqOQ==,type:str]
    pgp:
        - created_at: "2021-11-23T16:15:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf9G7BAXL7L+FvDCsGD5rRgY2Zv+nPeIW2Hm+M+gUO4lyK6
            6RgYkvjE4x7I6mySwYjG2uX023RGavgIDPgeTGXke1tARRGUGysmzp59WLIdUrby
            fNnV3lKUwGoD/7X1AsIb+DDvOvuO2j0Anv9fNzIGEd8coV7YGjvl+m+X5AyIgnxu
            OWiJSbUxZbljnV9WrxpaVpCo6PtulmQXUD+9WRCj7ii4HUxv6NRwVi4yawXuR7pI
            5Mpz3OK/48SArBxxjgXlAf+wr8ZIptWJIMvxRr8pZMnNY7lffCJbmMpC7xtdO83x
            hT4z/AF4PWgYsxsM8cchBMbdjBkxiKeh+pf2L9c0XtJeAV1yIXqkT4wlYgPHPZCk
            bEZseXHbJzLp74WlempkVHWISJ3eHcSSshSpepj3+KT2IA1tQJdak5mTmR4GkT7S
            uu2carIeobyDglUhgF+nnJDsxwVJrRVBHeAQ04J6rQ==
            =Qw6n
            -----END PGP MESSAGE-----
          fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.7.1
