apiVersion: v1
kind: Secret
metadata:
    name: trino-ldap-settings
stringData:
    ldap-bind-password: ENC[AES256_GCM,data:ZVRjHOXRztGKWd6tMq5sIGtksAKikqIFNO1NYR5A9R0=,iv:/qWlZfc8oaMNFEkMtm8v5c362PFyUdazUrN7lCy0ZCA=,tag:fT57l1J35OydkJbNKdhiRw==,type:str]
    ldap-user-base-dn: ENC[AES256_GCM,data:KfVa4DpOEKA2SStsrsv/I90/MGnaBypYdA==,iv:YEPsLq3heu63NFAUzBboNw2VK9S+sn35zwunCc43BTE=,tag:yc3KZyPWMhkm62ZAg4I/NA==,type:str]
    ldap-group-base-dn: ENC[AES256_GCM,data:wXWLDNcNsSD5IjHBXBx6P5kY90f7+ecVSQ9kSYM0Qmph8pcJIhmV5Qc2,iv:xlNvxq+sgyCMrtBBRH6nz9wydV/k5CD1+XByvmEOhu8=,tag:oflsWRaqof7I2V3V9yJSMA==,type:str]
    ldap-bind-dn: ENC[AES256_GCM,data:Vboc3Hx4GV4eAGgc9nKLlzfZPR9+TUSD0X0irBNcw8AJgi4Bs74SlIg=,iv:84GC15LyyBfVsU4FMmFLBUZglEwNy3S+x8D2S480ahM=,tag:MEu1K59Upve3nZP2HVAXhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-08-19T23:45:18Z'
    mac: ENC[AES256_GCM,data:y8emGl/morWkWGykxHu/2RAZggZFhchxpkAVyDF9A/IwTLkqbHnvsIaxY345MAaWS/6ilQRV2frHmcotcB+RfWrm72Fe0+w3/vTzS7Y4IxfJfIA5bDqoLbN6icw4Mr1Oznv8rGELq98s6fXQo+FtMu/Tv1zSc78JjKJBgwIM3Xs=,iv:jgfUmzKc5Uo2mFNGW0jareEbp0o8wxOZAHJ7mQ69Mxc=,tag:ieJYMfDsCOGdmIBCnjNykw==,type:str]
    pgp:
    -   created_at: '2022-08-19T20:17:43Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf7BrWwbLcJuZbupY3rgQMM0f/nm5zobbECVyzajqbAzWzy
            UDsnddg5J8e8Uqu+BVMtXxXmlsg8qdMVi7dtR7apJcPtn6D7Flko6f/bwJyiBNpb
            mGddjEEP3LaGogB7EN6bUuFoSxvPTEu6MSiQ8wYfEZ7YMN50HpUPZ4znNDJV5230
            v0G7C+gm7EErVhYPNFUu2dBpg2cVcHPaLSlOeBMNGH4Vjf7+3i+BYtLzR7u+DOVN
            UrhZLAx9wWg+FbFP/7QPRuRGOqVcM/9NHGdu2O0DrqEtG2gMNFclkkqd1+ZvIKHT
            JOgEM6qA/WrEx5wVN55iOKJf6LFvEJu5MBom79CVUtJeAfu+CUB50Gs7CssbI8Fi
            9oxiKckGIyq+0k9YOrQl762blgq/SBm6KAs0ltMzoO9K+/s0pXK+sSr3Tw7BZTgb
            LI2tHalrcW/VY/IQ7FRiWFUzRZsUpdHZAIP1tTfeIw==
            =Ssqk
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
