apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trino-service-monitor
spec:
  jobLabel: prometheus.io/joblabel
  endpoints:
    - interval: 30s
      path: /
      port: metrics
  namespaceSelector:
    matchNames:
      - dh-dev-trino
      - dh-prod-trino
      - dh-stage-trino
  selector:
    matchLabels:
      prometheus.io/scrape: "true"
