kind: Deployment
apiVersion: apps/v1
metadata:
  name: trino-worker
  labels:
    component.opendatahub.io/name: trino
    instance: trino
    opendatahub.io/component: 'true'
    role: trino-worker
spec:
  template:
    spec:
      volumes:
        - name: trino-config-volume
          secret:
            secretName: trino-config
            items:
              - key: config-worker.properties
                path: config-worker.properties
              - key: log.properties
                path: log.properties
              - key: node.properties
                path: node.properties
        - name: trino-jvm-worker-config
          secret:
            secretName: trino-jvm-worker-config
            items:
              - key: jvm-worker.config
                path: jvm-worker.config
            defaultMode: 420
        - name: root-ca
          secret:
            secretName: root-ca
            items:
              - key: RH-IT-Root-CA.crt
                path: RH-IT-Root-CA.crt
            defaultMode: 420
        - name: trino-catalogs-volume
          secret:
            secretName: trino-catalog
            defaultMode: 420
            items:
              - key: hive.properties
                path: hive.properties
              - key: jmx.properties
                path: jmx.properties
              - key: prometheus.properties
                path: prometheus.properties
              - key: iceberg.properties
                path: iceberg.properties
        - name: trino-truststore
          secret:
            secretName: trino-truststore
            defaultMode: 420
        - name: trino-telemetry-sa-token
          secret:
            secretName: trino-telemetry-sa-token
            defaultMode: 420
      initContainers:
        - name: trino-memory-limit
          image: 'registry.access.redhat.com/ubi8/ubi-minimal:8.4-208' # TODO: Check which image to use
          resources:
            limits:
              cpu: 150m
              memory: 50Mi
            requests:
              cpu: 150m
              memory: 20Mi
          command:
            - /bin/sh
            - -c
            - >
              get_memory_limit() {
                  # TODO: Get memory limit and cast into a number
                  MEMORY_LIMIT=${25Gi/Gi/""}
              }
              get_percentages() {
                  # TODO: Get the percentages  
                  MAX_MEMORY_PER_NODE_PERCENTAGE=0.1
                  MAX_TOTAL_MEMORY_PER_NODE_PERCENTAGE=0.3
                  MAX_MEMORY_PERCENTAGE=0.5
              }

              calc_values() { awk "BEGIN{ printf \"%.0f\n\", $* }"; }

              get_memory_limit
              get_percentages

              # calculate memory with the percentages
              max_memory_per_node=$(calc_values $MEMORY_LIMIT*$MAX_MEMORY_PER_NODE_PERCENTAGE)
              max_total_memory_per_node=$(calc_values $MEMORY_LIMIT*$MAX_TOTAL_MEMORY_PER_NODE_PERCENTAGE)
              max_memory=$(calc_values $MEMORY_LIMIT*$MAX_MEMORY_PERCENTAGE)

              # TODO: Set Up the values

              echo "${max_memory_per_node}GB"
              echo "${max_total_memory_per_node}GB"
              echo "${max_memory}GB"

      containers:
        - name: trino-worker
          args:
            - --config=/etc/trino/config-worker.properties
            - --jvm-config=/etc/trino/jvm-config/jvm-worker.config
          volumeMounts:
            - name: trino-config-volume
              mountPath: /etc/trino
            - name: trino-catalogs-volume
              mountPath: /etc/trino/catalog
            - name: root-ca
              mountPath: /etc/certs
            - name: trino-truststore
              mountPath: /etc/trino/certs
            - name: trino-jvm-worker-config
              mountPath: /etc/trino/jvm-config
            - name: trino-telemetry-sa-token
              mountPath: /etc/trino/telemetry-sa-token
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - trino-worker
                topologyKey: topology.kubernetes.io/zone
