apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator
  labels:
    instance: trino
    role: trino-coordinator
spec:
  selector:
    matchLabels:
      instance: trino
      role: trino-coordinator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        instance: trino
        role: trino-coordinator
    spec:
      volumes:
        - name: root-ca
          secret:
            secretName: root-ca
            items:
              - key: RH-IT-Root-CA.crt
                path: RH-IT-Root-CA.crt
        - name: prometheus-exporter
          secret:
            secretName: trino-config-monitoring
            items:
              - key: config.yaml
                path: config.yaml
            defaultMode: 420
        - name: trino-config-volume
          secret:
            secretName: trino-config
            items:
              - key: config-coordinator.properties
                path: config-coordinator.properties
              - key: log.properties
                path: log.properties
              - key: node.properties
                path: node.properties
              - key: ldap-authenticator.properties
                path: ldap-authenticator.properties
              - key: file-authenticator.properties
                path: file-authenticator.properties
              - key: password.db
                path: password.db
              - key: access-control.properties
                path: access-control.properties
              - key: rules.json
                path: rules.json
              - key: group-provider.properties
                path: group-provider.properties
              - key: group-mapping.properties
                path: group-mapping.properties
        - name: trino-acls-volume
          secretName: trino-acls
        - name: trino-catalogs-volume
          secret:
            secretName: trino-catalog
            defaultMode: 420
            items:
              - key: hive.properties
                path: hive.properties
              - key: jmx.properties
                path: jmx.properties
              - key: prometheus.properties
                path: prometheus.properties
              - key: iceberg.properties
                path: iceberg.properties
        - name: trino-jvm-coordinator-config
          secret:
            secretName: trino-jvm-coordinator-config
            items:
              - key: jvm-coordinator.config
                path: jvm-coordinator.config
            defaultMode: 420
        - name: trino-truststore
          secret:
            secretName: trino-truststore
            defaultMode: 420
        - name: trino-telemetry-sa-token
          secret:
            secretName: trino-telemetry-sa-token
            defaultMode: 420
      containers:
        - resources:
            requests:
              cpu: $(trino_cpu_request)
              memory: $(trino_memory_request)
            limits:
              cpu: $(trino_cpu_limit)
              memory: $(trino_memory_limit)
          name: trino-coordinator
          args:
            - --config=/etc/trino/config-coordinator.properties
            - --jvm-config=/etc/trino/jvm-config/jvm-coordinator.config
          command:
            - /usr/lib/trino/bin/run-trino
          env:
            - name: POD_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.uid
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: $(s3_credentials_secret)
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: $(s3_credentials_secret)
                  key: AWS_SECRET_ACCESS_KEY
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: trino-config-volume
              mountPath: /etc/trino
            - name: trino-catalogs-volume
              mountPath: /etc/trino/catalog
            - name: root-ca
              mountPath: /etc/certs
            - name: prometheus-exporter
              mountPath: /etc/trino/prometheus
            - name: trino-truststore
              mountPath: /etc/trino/certs
            - name: trino-jvm-coordinator-config
              mountPath: /etc/trino/jvm-config
            - name: trino-telemetry-sa-token
              mountPath: /etc/trino/telemetry-sa-token
            - name: trino-acls-volume
              mountPath: /etc/trino-acls
