- job_name: 'Rsyslog Availability'
  metrics_path: '/probe'
  params:
    module: [tcp_ingest]
  scrape_interval: 30s
  kubernetes_sd_configs:
    - role: service
      namespaces:
        names:
        - dh-prod-ingest
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name]
    regex: ^.*(rsyslog-external)$
    action: keep
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-prober.dh-psi-monitoring.svc.cluster.local
