---
varReference:
  - path: data
    kind: ConfigMap
  - path: stringData
    kind: Secret
  - path: metadata/annotations/volume.beta.kubernetes.io\/storage-class
    kind: PersistentVolumeClaim
  - path: spec/template/spec/containers[]/resources/requests/cpu
    kind: Deployment
  - path: spec/template/spec/containers[]/resources/limits/cpu
    kind: Deployment
  - path: spec/template/spec/containers[]/resources/requests/memory
    kind: Deployment
  - path: spec/template/spec/containers[]/resources/limits/memory
    kind: Deployment
  - path: spec/template/spec/containers[]/envFrom/secretRef/name
    kind: Deployment
  - path: spec/template/spec/initContainers[]/envFrom/secretRef/name
    kind: Deployment
  - path: spec/template/spec/containers[]/env[]/valueFrom/secretKeyRef/name
    kind: Deployment
  - path: spec/template/spec/initContainers[]/env[]/valueFrom/secretKeyRef/name
    kind: Deployment
