apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: superset-rbac-viewer
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
