namespace: dh-prod-ingest
resources:
  - ../../bases/logstash
  - ../../bases/viewer_rolebindings
  - ../../bases/admin_rolebindings
patchesStrategicMerge:
  - logstash.yaml
generators:
  - ./secrets/secret-generator.yaml
configMapGenerator:
  - name: logstash-ingest-logstash-config
    behavior: merge
    files:
      - logstash-conf/99-output-kafka.conf
