apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blackbox-alerting-rules
spec:
  groups:
    - name: SLOs-probe_success
      rules:
      - alert: Data Hub Probe Success Burn Rate
        annotations:
          message: 'High error budget burn for {{ $labels.target }} (current value: {{ $value }}).'
          summary: Data Hub Route Error Burn Rate
        expr: |
          sum(probe_success:burnrate5m{target=~".*datahub.*"}) by (target) > (14.40 * (1-0.98000))
          and
          sum(probe_success:burnrate1h{target=~".*datahub.*"}) by (target) > (14.40 * (1-0.98000))
        for: 2m
        labels:
          severity: critical
          datahubalert: "true"
      - alert: Data Hub Probe Success Burn Rate
        annotations:
          message: 'High error budget burn for {{ $labels.target }} (current value: {{ $value }}).'
          summary: Data Hub Route Error Burn Rate
        expr: |
          sum(probe_success:burnrate30m{target=~".*datahub.*"}) by (target) > (6.00 * (1-0.98000))
          and
          sum(probe_success:burnrate6h{target=~".*datahub.*"}) by (target) > (6.00 * (1-0.98000))
        for: 15m
        labels:
          severity: critical
          datahubalert: "true"
      - alert: Data Hub Probe Success Burn Rate
        annotations:
          message: 'High error budget burn for {{ $labels.target }} (current value: {{ $value }}).'
          summary: Data Hub Route Error Burn Rate
        expr: |
          sum(probe_success:burnrate2h{target=~".*datahub.*"}) by (target) > (3.00 * (1-0.98000))
          and
          sum(probe_success:burnrate1d{target=~".*datahub.*"}) by (target) > (3.00 * (1-0.98000))
        for: 1h
        labels:
          severity: warning
          datahubalert: "true"
      - alert: Data Hub Probe Success Burn Rate
        annotations:
          message: 'High error budget burn for {{ $labels.target }} (current value: {{ $value }}).'
          summary: Data Hub Route Error Burn Rate
        expr: |
          sum(probe_success:burnrate6h{target=~".*datahub.*"}) by (target) > (1.00 * (1-0.98000))
          and
          sum(probe_success:burnrate3d{target=~".*datahub.*"}) by (target) > (1.00 * (1-0.98000))
        for: 3h
        labels:
          severity: warning
          datahubalert: "true"
