apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blackbox-recording-rules
spec:
  groups:
    - name: SLOs - Data Hub Route Probes
      rules:
        - expr: |
            1 - avg_over_time(probe_success{target=~".*datahub.*", job="blackbox-metrics"}[5m])
          record: probe_success:burnrate5m
        - expr: |
            1 - avg_over_time(probe_success{target=~".*datahub.*", job="blackbox-metrics"}[30m])
          record: probe_success:burnrate30m
        - expr: |
            1 - avg_over_time(probe_success{target=~".*datahub.*", job="blackbox-metrics"}[1h])
          record: probe_success:burnrate1h
        - expr: |
            1 - avg_over_time(probe_success{target=~".*datahub.*", job="blackbox-metrics"}[2h])
          record: probe_success:burnrate2h
        - expr: |
            1 - avg_over_time(probe_success{target=~".*datahub.*", job="blackbox-metrics"}[6h])
          record: probe_success:burnrate6h
        - expr: |
            1 - avg_over_time(probe_success{target=~".*datahub.*", job="blackbox-metrics"}[1d])
          record: probe_success:burnrate1d
        - expr: |
            1 - avg_over_time(probe_success{target=~".*datahub.*", job="blackbox-metrics"}[3d])
          record: probe_success:burnrate3d  # This metric is currently identical to 1d as cluster retention policy is only 1 day
