---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blackbox-exporter
    prometheus.io/scrape: "true"
    prometheus.io/joblabel: "blackbox-metrics"
  name: blackbox-exporter
spec:
  ports:
  - name: 9115-tcp
    port: 9115
    protocol: TCP
    targetPort: 9115
  selector:
    deployment: blackbox-exporter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 10s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          method: GET
          valid_status_codes: [200, 201, 202, 203, 204, 205, 206, 207, 208, 403]
          preferred_ip_protocol: "ip4"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: blackbox-exporter
  name: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: blackbox-exporter
  template:
    metadata:
      labels:
        deployment: blackbox-exporter
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: blackbox
      containers:
      - image: quay.io/integreatly/prometheus-blackbox-exporter:v0.19.0
        name: blackbox-exporter
        args:
        - --log.level=debug
        - --config.file=/tmp/blackbox.yml
        volumeMounts:
        - name: config-volume
          mountPath: /tmp
        ports:
        - containerPort: 9115
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9115
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /-/healthy
            port: 9115
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
      restartPolicy: Always
      progressDeadlineSeconds: 2400
