---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - secret-generator.yaml

resources:
  - blackbox-alerting-rules.yaml
  - blackbox-exporter.yaml
  - blackbox-recording-rules.yaml
  - datahub-help-blackbox-service-monitor.yaml
  - trino-blackbox-service-monitor.yaml
