---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - secret-generator.yaml

resources:
  - blackbox-alerting-rules.yaml
  - blackbox-exporter.yaml
  - blackbox-recording-rules.yaml
  - datahub-help-blackbox-service-monitor.yaml
  - trino-blackbox-service-monitor.yaml
  - superset-blackbox-service-monitor.yaml
  - jupyterhub-blackbox-service-monitor.yaml
  - cvp-s3-webserver-blackbox-service-monitor.yaml
  - telemeter-lts-dashboards-blackbox-service-monitor.yaml
  - telemeter-lts-blackbox-service-monitor.yaml
