apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: telemeter-lts-blackbox-service-monitor
spec:
  endpoints:
    - interval: 30s
      metricRelabelings:
        - sourceLabels:
            - __address__
          targetLabel: __param_target
        - sourceLabels:
            - __param_target
          targetLabel: instance
        - replacement: 'https://telemeter-lts.datahub.redhat.com/-/healthy'
          targetLabel: target
      params:
        module:
          - http_2xx
        target:
          - 'https://telemeter-lts.datahub.redhat.com/-/healthy'
      path: /probe
      targetPort: 9115
  jobLabel: prometheus.io/joblabel
  namespaceSelector:
    matchNames:
      - dh-dev-monitoring
      - dh-stage-monitoring
      - dh-prod-monitoring
  selector:
    matchLabels:
      prometheus.io/scrape: 'true'
