name: Approved-Labeler
on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  approved-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: Amwam/issue-comment-action@v1.3.1
        with:
          keywords: '["/approve"]'
          labels: '["approved"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
